{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.901.0 (24.07)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Data\",\"Sample File\",\"Parameter1\",\"Transform Sample File\",\"Transform File\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\EndToEndProjectSalesDashboard\\Data\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "5aba449c-5dda-4d49-9ae7-b0b99e5b6a67",
        "queryGroup": "Transform File from Data\\Helper Queries"
      },
      {
        "name": "Parameter1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "2e39c97b-4c8d-478b-b538-333d9f8e5bbb",
        "queryGroup": "Transform File from Data\\Helper Queries"
      },
      {
        "name": "Transform Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(Parameter1,[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "29aad667-6879-4d17-922a-d078b2d4b1a7",
        "queryGroup": "Transform File from Data"
      },
      {
        "name": "Transform File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter1) => let",
          "        Source = Csv.Document(Parameter1,[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "        #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "    in",
          "        #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "5f47bb9a-1767-4596-9cfc-55086c020195",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File\"\"}\" ]",
        "queryGroup": "Transform File from Data\\Helper Queries"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Data"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Data\\Helper Queries"
      }
    ],
    "roles": [
      {
        "name": "Portland",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e9f1dd2868904c68a8f1c75b3d389715"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Data",
            "filterExpression": "[Region] == \"Portland\""
          }
        ]
      },
      {
        "name": "San Francisco",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "264eb02a82f44d05b055a5c84655439a"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Data",
            "filterExpression": "[Region] == \"San Francisco\""
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a8632405-73e3-4891-badf-c2683afa9f97",
            "sourceColumn": "Order ID",
            "summarizeBy": "count"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c496d26-d240-4247-8266-a31b197021d1",
            "sourceColumn": "Product",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity Ordered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a1592abe-2b38-4dcf-9f1c-385d02b39de0",
            "sourceColumn": "Quantity Ordered",
            "summarizeBy": "sum"
          },
          {
            "name": "Price Each",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3cc2df38-8dbd-4be7-a407-4ae45c2d8352",
            "sourceColumn": "Price Each",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8d542133-3832-4930-9f0c-4458029573a0",
            "sourceColumn": "Order Date",
            "summarizeBy": "none"
          },
          {
            "name": "Purchase Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f170584b-4f58-4a29-b47e-954e36e4e6bb",
            "sourceColumn": "Purchase Address",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "45b622df-d63b-49a8-9d66-01e44e4c5e7e",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR(Data[Order Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "3db38549-750d-43e0-89f1-608c6da5e7a8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH(Data[Order Date]) ",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "50d656b4-29cc-4588-99b7-3a51c659aec0",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(Data[Order Date],\"mmm\")",
            "isDataTypeInferred": true,
            "lineageTag": "4c7a5d41-aee9-4a71-ae8d-cc1a0d9f3bad",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "Data[Quantity Ordered] * Data[Price Each]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "isDataTypeInferred": true,
            "lineageTag": "f3c8eaa8-ec67-4dc2-978d-241cd209468c",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "f40eee5b-9421-493d-a5de-7976b92e7057",
        "partitions": [
          {
            "name": "Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\EndToEndProjectSalesDashboard\\Data\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File\", each #\"Transform File\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File\"(#\"Sample File\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"Order ID\", type text}, {\"Product\", type text}, {\"Quantity Ordered\", type text}, {\"Price Each\", type text}, {\"Order Date\", type text}, {\"Purchase Address\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Source.Name\"}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Removed Columns\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Blank Rows\",{{\"Order ID\", Int64.Type}, {\"Quantity Ordered\", Int64.Type}, {\"Price Each\", type number}}),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Changed Type1\", {\"Order ID\"}),",
                "    #\"Changed Type with Locale\" = Table.TransformColumnTypes(#\"Removed Errors\", {{\"Order Date\", type datetime}}, \"en-US\"),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Changed Type with Locale\",{{\"Order Date\", type date}}),",
                "    #\"Inserted Text Between Delimiters\" = Table.AddColumn(#\"Changed Type2\", \"Text Between Delimiters\", each Text.BetweenDelimiters([Purchase Address], \",\", \",\"), type text),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Text Between Delimiters\",{{\"Text Between Delimiters\", \"Region\"}}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Renamed Columns\",{{\"Region\", Text.Trim, type text}})",
                "in",
                "    #\"Trimmed Text\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}