{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.754.0 (24.06)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Territory Lookup\",\"Product Lookup\",\"Product Categories Lookup\",\"Product Subcategories Lookup\",\"Largest Asset Management Firms\",\"Customer Lookup\",\"Calendar Lookup\",\"Rolling Calendar\",\"Sales Data\",\"Parameter1\",\"Transform Sample File\",\"Sample File\",\"Transform File\",\"Returns Data\",\"Measure Table\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Largest Asset Management Firms",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.BrowserContents(\"https://en.wikipedia.org/wiki/List_of_asset_management_firms\"),",
          "    #\"Extracted Table From Html\" = Html.Table(Source, {{\"Column1\", \"TABLE.sortable.wikitable > * > TR > :nth-child(1)\"}, {\"Column2\", \"TABLE.sortable.wikitable > * > TR > :nth-child(2)\"}, {\"Column3\", \"TABLE.sortable.wikitable > * > TR > :nth-child(3)\"}, {\"Column4\", \"TABLE.sortable.wikitable > * > TR > :nth-child(4)\"}}, [RowSelector=\"TABLE.sortable.wikitable > * > TR\"]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Extracted Table From Html\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Rank\", Int64.Type}, {\"Firm/company\", type text}, {\"Country\", type text}, {\"AUM (billion USD)\", type number}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "177fe23f-fda7-40a9-a851-853c586d6f99",
        "queryGroup": "Demo Queries"
      },
      {
        "name": "Parameter1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "1440b449-fc50-4e69-86d1-73e0e8e96d82",
        "queryGroup": "Transform File from Sales Data\\Helper Queries"
      },
      {
        "name": "Transform Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(Parameter1,[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "313eafb4-dfd8-4605-9810-74db992996bb",
        "queryGroup": "Transform File from Sales Data"
      },
      {
        "name": "Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(\"C:\\Users\\Pranav Bhoola\\Desktop\\MicrosoftPowerBIDesktopForBusinessIntelligence\\Sales Data\"),",
          "    #\"C:\\Users\\Pranav Bhoola\\Desktop\\MicrosoftPowerBIDesktopForBusinessIntelligence\\Sales Data\\_AdventureWorks Sales Data 2021 csv\" = Source{[#\"Folder Path\"=\"C:\\Users\\Pranav Bhoola\\Desktop\\MicrosoftPowerBIDesktopForBusinessIntelligence\\Sales Data\\\",Name=\"AdventureWorks Sales Data 2021.csv\"]}[Content]",
          "in",
          "    #\"C:\\Users\\Pranav Bhoola\\Desktop\\MicrosoftPowerBIDesktopForBusinessIntelligence\\Sales Data\\_AdventureWorks Sales Data 2021 csv\""
        ],
        "kind": "m",
        "lineageTag": "c653d9b6-fdde-4597-8904-d72316d241ce",
        "queryGroup": "Transform File from Sales Data\\Helper Queries"
      },
      {
        "name": "Transform File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter1 as binary) => let",
          "    Source = Csv.Document(Parameter1,[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "f0c28b3a-f99b-4831-883a-f1a88ca8bef3",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File\"\"}\" ]",
        "queryGroup": "Transform File from Sales Data\\Helper Queries"
      },
      {
        "name": "Rolling Calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = #date(2023,1,1),",
          "    Custom1 = List.Dates(",
          "    Source,",
          "    Number.From(DateTime.LocalNow()) - Number.From(Source),",
          "    #duration(1,0,0,0)",
          "),",
          "    #\"Converted to Table\" = Table.FromList(Custom1, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"Date\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Date\", type date}}),",
          "    #\"Inserted Year\" = Table.AddColumn(#\"Changed Type\", \"Year\", each Date.Year([Date]), Int64.Type),",
          "    #\"Inserted Start of Quarter\" = Table.AddColumn(#\"Inserted Year\", \"Start of Quarter\", each Date.StartOfQuarter([Date]), type date),",
          "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Inserted Start of Quarter\", \"Start of Month\", each Date.StartOfMonth([Date]), type date)",
          "in",
          "    #\"Inserted Start of Month\""
        ],
        "kind": "m",
        "lineageTag": "408fa17f-e128-4341-afc1-483f9e46158f",
        "queryGroup": "Demo Queries"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Demo Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Transform File from Sales Data"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Sales Data\\Helper Queries"
      }
    ],
    "relationships": [
      {
        "name": "2344e6b8-871a-693e-d634-7c20b2247786",
        "fromColumn": "TerritoryKey",
        "fromTable": "Sales Data",
        "toColumn": "SalesTerritoryKey",
        "toTable": "Territory Lookup"
      },
      {
        "name": "8945600e-a32b-f84c-9ef3-e0f0d9c31a99",
        "fromColumn": "CustomerKey",
        "fromTable": "Sales Data",
        "toColumn": "CustomerKey",
        "toTable": "Customer Lookup"
      },
      {
        "name": "a6a94ebe-65be-60a0-2850-41f79f0bff4f",
        "fromColumn": "OrderDate",
        "fromTable": "Sales Data",
        "toColumn": "Date",
        "toTable": "Calendar Lookup"
      },
      {
        "name": "82c17b86-9942-fc9d-d183-9355d59c0f9f",
        "fromColumn": "ProductKey",
        "fromTable": "Sales Data",
        "toColumn": "ProductKey",
        "toTable": "Product Lookup"
      },
      {
        "name": "75f11a05-4761-3dbb-62b3-82874e4ee51b",
        "fromColumn": "ProductSubcategoryKey",
        "fromTable": "Product Lookup",
        "toColumn": "ProductSubcategoryKey",
        "toTable": "Product Subcategories Lookup"
      },
      {
        "name": "29ffbd64-9a8c-fb91-d3f3-83d673c13a5d",
        "fromColumn": "ProductCategoryKey",
        "fromTable": "Product Subcategories Lookup",
        "toColumn": "ProductCategoryKey",
        "toTable": "Product Categories Lookup"
      },
      {
        "name": "26eb4c55-6e82-dd27-469b-074d43a958e9",
        "fromColumn": "StockDate",
        "fromTable": "Sales Data",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar Lookup"
      },
      {
        "name": "ba48cb18-1088-feba-7533-34efd0ef82f9",
        "fromColumn": "ProductKey",
        "fromTable": "Returns Data",
        "toColumn": "ProductKey",
        "toTable": "Product Lookup"
      },
      {
        "name": "85f375db-dda5-0805-53ef-252851bc4aa1",
        "fromColumn": "ReturnDate",
        "fromTable": "Returns Data",
        "toColumn": "Date",
        "toTable": "Calendar Lookup"
      },
      {
        "name": "4931e3f7-524e-1a80-3fa4-1758f07f7c22",
        "fromColumn": "TerritoryKey",
        "fromTable": "Returns Data",
        "toColumn": "SalesTerritoryKey",
        "toTable": "Territory Lookup"
      }
    ],
    "roles": [
      {
        "name": "Europe",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c008dedac091458590ba4329830e851f"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Territory Lookup",
            "filterExpression": "[Continent] == \"Europe\""
          }
        ]
      },
      {
        "name": "North America",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "09500943a99e483089f30eec25acd8e7"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Territory Lookup",
            "filterExpression": "[Continent] == \"North America\""
          }
        ]
      },
      {
        "name": "Pacific",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1d57ecb638e544d0a8c2a9df1ceedd1f"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Territory Lookup",
            "filterExpression": "[Continent] == \"Pacific\""
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Territory Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "5879c8ef-7db2-4d96-892f-d023a7093749",
            "sourceColumn": "SalesTerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cef582b5-ff42-4411-bb66-10135da3dad7",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "lineageTag": "88b7096c-e804-4183-b12c-3ba04831b287",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Continent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Continent",
            "dataType": "string",
            "lineageTag": "46023772-44de-4132-b037-761d0355b203",
            "sourceColumn": "Continent",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "hierarchies": [
          {
            "name": "Territory Hierarchy",
            "levels": [
              {
                "name": "Continent",
                "column": "Continent",
                "lineageTag": "4156cb51-ea0a-428b-9a23-3d94ac9174cd",
                "ordinal": 0
              },
              {
                "name": "Country",
                "column": "Country",
                "lineageTag": "4e07e1fa-67f3-475c-b325-308751ee0303",
                "ordinal": 1
              }
            ],
            "lineageTag": "efbd6162-d469-4e3f-86eb-5d8691c316b1"
          }
        ],
        "lineageTag": "b587c13d-3627-4fba-87f4-f401be9991a5",
        "partitions": [
          {
            "name": "Territory Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\MicrosoftPowerBIDesktopForBusinessIntelligence\\AdventureWorksRawData\\AdventureWorks Territory Lookup.csv\"),[Delimiter=\",\", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SalesTerritoryKey\", Int64.Type}, {\"Region\", type text}, {\"Country\", type text}, {\"Continent\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "cc0b2207-a744-4972-85eb-f52c8e309ad5",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2941a8b0-0901-440e-9ccc-e21778ade93b",
            "sourceColumn": "ProductSubcategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSKU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0648c0bc-f340-423a-8797-991f2f66a014",
            "sourceColumn": "ProductSKU",
            "summarizeBy": "none"
          },
          {
            "name": "ProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f823a7de-4b7c-42e4-87c2-6a590f6444cc",
            "sourceColumn": "ProductName",
            "summarizeBy": "none"
          },
          {
            "name": "ModelName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d7d7a9c-7c01-470c-8225-477def45240b",
            "sourceColumn": "ModelName",
            "summarizeBy": "none"
          },
          {
            "name": "ProductDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0fd6dbcc-1c5f-4b2f-9b89-62bc00efcb17",
            "sourceColumn": "ProductDescription",
            "summarizeBy": "none"
          },
          {
            "name": "ProductColor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a0e2b06-01ad-4dff-b358-84bc269683c5",
            "sourceColumn": "ProductColor",
            "summarizeBy": "none"
          },
          {
            "name": "ProductStyle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b9849a8-fb1a-4816-97aa-2446337b8e6f",
            "sourceColumn": "ProductStyle",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R\"#,0.00;-\"R\"#,0.00;\"R\"#,0.00",
            "lineageTag": "6c020f0d-8bfd-45b9-846a-a8e3e183687b",
            "sourceColumn": "ProductCost",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R\"#,0.00;-\"R\"#,0.00;\"R\"#,0.00",
            "lineageTag": "a491d8ff-d78a-4ae9-8cae-c5a8b45a707a",
            "sourceColumn": "ProductPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "SKU Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ae92271-e045-424e-b0f0-2609625eb796",
            "sourceColumn": "SKU Type",
            "summarizeBy": "none"
          },
          {
            "name": "Discount Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R\"#,0.00;-\"R\"#,0.00;\"R\"#,0.00",
            "lineageTag": "86d4810b-84f8-446f-bbf5-1987a0812f4b",
            "sourceColumn": "Discount Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Price Point",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              " SWITCH(",
              "    TRUE(),",
              "    'Product Lookup'[ProductPrice] > 500 , \"High\",",
              "    'Product Lookup'[ProductPrice] > 100 , \"Mid-Range\",",
              "    \"Low\"",
              " )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "8ff5d0b2-aa85-4b1d-9ff6-8e5904e738b7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "SKU Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "LEFT(",
              "    'Product Lookup'[ProductSKU],",
              "    SEARCH(",
              "        \"-\",",
              "        'Product Lookup'[ProductSKU]",
              "    )",
              "    -1",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "602933c0-3ee9-4b38-9628-023d71e964fc",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "2fb06944-b997-478e-8bc4-31af0c4ccd01",
        "partitions": [
          {
            "name": "Product Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\MicrosoftPowerBIDesktopForBusinessIntelligence\\AdventureWorksRawData\\AdventureWorks Product Lookup.csv\"),[Delimiter=\",\", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductKey\", Int64.Type}, {\"ProductSubcategoryKey\", Int64.Type}, {\"ProductSKU\", type text}, {\"ProductName\", type text}, {\"ModelName\", type text}, {\"ProductDescription\", type text}, {\"ProductColor\", type text}, {\"ProductSize\", type text}, {\"ProductStyle\", type text}, {\"ProductCost\", Currency.Type}, {\"ProductPrice\", type number}}),",
                "    #\"Changed to Currency\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"ProductCost\", Currency.Type}, {\"ProductPrice\", Currency.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed to Currency\",{\"ProductSize\"}),",
                "    #\"Inserted Text Before Delimiter\" = Table.AddColumn(#\"Removed Columns\", \"Text Before Delimiter\", each Text.BeforeDelimiter([ProductSKU], \"-\", 1), type text),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Inserted Text Before Delimiter\",{{\"Text Before Delimiter\", \"SKU Type\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns1\",\"0\",\"NA\",Replacer.ReplaceText,{\"ProductStyle\"}),",
                "    #\"Inserted Multiplication\" = Table.AddColumn(#\"Replaced Value\", \"Multiplication\", each [ProductPrice] * 0.9, Currency.Type),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Multiplication\",{{\"Multiplication\", \"Discount Price\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Categories Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "798ab5c6-aee3-4032-9431-e53aebd42f29",
            "sourceColumn": "ProductCategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "CategoryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cbfef8b8-0e7d-4138-8bf0-5d713b7b10ac",
            "sourceColumn": "CategoryName",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "f7389485-2023-4b7b-8fef-70ada596a05a",
        "partitions": [
          {
            "name": "Product Categories Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\MicrosoftPowerBIDesktopForBusinessIntelligence\\AdventureWorksRawData\\AdventureWorks Product Categories Lookup.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductCategoryKey\", Int64.Type}, {\"CategoryName\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Subcategories Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "d72ca9ab-7cc2-4c77-9b4a-72159ed8b423",
            "sourceColumn": "ProductSubcategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "SubcategoryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b66eba37-4f34-4f68-8d46-fa5b48ac5c6b",
            "sourceColumn": "SubcategoryName",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8bb66faf-2b4d-4b6d-8673-168de70ee4a7",
            "sourceColumn": "ProductCategoryKey",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "db7d8af1-a754-421f-938d-eb4842b1ed96",
        "partitions": [
          {
            "name": "Product Subcategories Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\MicrosoftPowerBIDesktopForBusinessIntelligence\\AdventureWorksRawData\\AdventureWorks Product Subcategories Lookup.csv\"),[Delimiter=\",\", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductSubcategoryKey\", Int64.Type}, {\"SubcategoryName\", type text}, {\"ProductCategoryKey\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "5c28562f-ca4e-4783-aea5-729a2d5e3ac0",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "Prefix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32e3498f-5656-4feb-aa83-8e0b74f09b5c",
            "sourceColumn": "Prefix",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c41433c9-66ee-4c63-9084-cd31e03c58f8",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0665579d-513a-4025-b94e-d42ed5bb9b67",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "BirthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5b0f7e3c-9fa6-4398-8eca-ea6993a72e62",
            "sourceColumn": "BirthDate",
            "summarizeBy": "none"
          },
          {
            "name": "MaritalStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "722a8036-4da7-42f0-bfc2-fe0f24650709",
            "sourceColumn": "MaritalStatus",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f255077b-2f88-4c85-9513-f2c0c77dfaa7",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b848f483-824e-4627-877f-2e13c9bbf56d",
            "sourceColumn": "EmailAddress",
            "summarizeBy": "none"
          },
          {
            "name": "AnnualIncome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "200642e0-c9a6-4557-9b89-2056715d0238",
            "sourceColumn": "AnnualIncome",
            "summarizeBy": "none"
          },
          {
            "name": "TotalChildren",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "67b9e64b-5abf-445d-9e5a-034aa9175440",
            "sourceColumn": "TotalChildren",
            "summarizeBy": "none"
          },
          {
            "name": "EducationLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4678698f-9b36-4321-945d-27ecc56a0f97",
            "sourceColumn": "EducationLevel",
            "summarizeBy": "none"
          },
          {
            "name": "Occupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2056f21d-0c1f-4e30-916e-ad379f2362ed",
            "sourceColumn": "Occupation",
            "summarizeBy": "none"
          },
          {
            "name": "HomeOwner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08aa0bfc-4f56-4eab-a284-68245e38dd48",
            "sourceColumn": "HomeOwner",
            "summarizeBy": "none"
          },
          {
            "name": "Full Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1550d6d9-cc97-4c72-96b5-f314d10b5d25",
            "sourceColumn": "Full Name",
            "summarizeBy": "none"
          },
          {
            "name": "Domain Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0bf8ced7-29e9-495f-a7e1-14e7906b45f2",
            "sourceColumn": "Domain Name",
            "summarizeBy": "none"
          },
          {
            "name": "Parent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              " IF(",
              "    'Customer Lookup'[TotalChildren] > 0,",
              "    \"Yes\",",
              "    \"No\"",
              " )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "9c2b9f8e-f495-4fd2-96da-07d47ba1b9b9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Customer Priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    'Customer Lookup'[Parent] = \"Yes\" &&",
              "    'Customer Lookup'[AnnualIncome] > 100000,",
              "    \"Priority\",",
              "    \"Standard\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "8f59f43f-683c-4d52-ad38-6eddc602a2d2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Income Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF('Customer Lookup'[AnnualIncome] >= 150000, \"Very High\",",
              "IF('Customer Lookup'[AnnualIncome] >= 100000, \"High\",",
              "IF('Customer Lookup'[AnnualIncome] >= 50000, \"Average\",",
              "\"Low\")))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "03191f79-33bb-4f2f-a49c-84df07265559",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Education Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              " SWITCH(",
              "    'Customer Lookup'[EducationLevel],",
              "    \"High School\" , \"High School\",",
              "    \"Partial High School\" , \"High School\",",
              "    \"Bachelors\" , \"Undergrad\",",
              "    \"Partial College\" , \"Undergrad\",",
              "    \"Graduate Degree\" , \"Graduate\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e89529fb-472a-4adf-a82b-dc091dda863d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Customer Full Name (CC)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "'Customer Lookup'[Prefix] & \" \" & 'Customer Lookup'[FirstName] & \" \" & 'Customer Lookup'[LastName]"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "4ffe2533-105f-413c-9c3f-747d45b11f0a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Birth Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "YEAR(",
              "    'Customer Lookup'[BirthDate]",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "7374cc67-da76-4edd-a2e1-a3162122a312",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "787a04f5-26b2-4119-a771-f18af8e83856",
        "measures": [
          {
            "name": "Full Name (Customer Detail)",
            "expression": [
              "",
              " IF(",
              "    HASONEVALUE(",
              "        'Customer Lookup'[CustomerKey]",
              "    ),",
              "    MAX(",
              "        'Customer Lookup'[Full Name]",
              "    ),",
              "    \"Multiple Customers\"",
              " )"
            ],
            "lineageTag": "8cfe3b49-c911-4cd6-944b-8d88092131c1"
          }
        ],
        "partitions": [
          {
            "name": "Customer Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\MicrosoftPowerBIDesktopForBusinessIntelligence\\AdventureWorksRawData\\AdventureWorks Customer Lookup.csv\"),[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CustomerKey\", Int64.Type}, {\"Prefix\", type text}, {\"FirstName\", type text}, {\"LastName\", type text}, {\"BirthDate\", type date}, {\"MaritalStatus\", type text}, {\"Gender\", type text}, {\"EmailAddress\", type text}, {\"AnnualIncome\", Int64.Type}, {\"TotalChildren\", Int64.Type}, {\"EducationLevel\", type text}, {\"Occupation\", type text}, {\"HomeOwner\", type text}}),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Changed Type\", {\"CustomerKey\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Errors\", each [CustomerKey] <> null and [CustomerKey] <> \"\"),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Filtered Rows\",{{\"Prefix\", Text.Proper, type text}, {\"FirstName\", Text.Proper, type text}, {\"LastName\", Text.Proper, type text}}),",
                "    #\"Inserted Full Name Column\" = Table.AddColumn(#\"Capitalized Each Word\", \"Full Name\", each Text.Combine({[Prefix], [FirstName], [LastName]}, \" \"), type text),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Inserted Full Name Column\", \"EmailAddress\", \"EmailAddress - Copy\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Duplicated Column\",{{\"EmailAddress - Copy\", \"Domain Name\"}}),",
                "    #\"Extracted Text After Delimiter\" = Table.TransformColumns(#\"Renamed Columns\", {{\"Domain Name\", each Text.AfterDelimiter(_, \"@\"), type text}}),",
                "    #\"Extracted Text Before Delimiter\" = Table.TransformColumns(#\"Extracted Text After Delimiter\", {{\"Domain Name\", each Text.BeforeDelimiter(_, \".\"), type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Extracted Text Before Delimiter\",\"-\",\" \",Replacer.ReplaceText,{\"Domain Name\"}),",
                "    #\"Capitalized Each Word1\" = Table.TransformColumns(#\"Replaced Value\",{{\"Domain Name\", Text.Proper, type text}})",
                "in",
                "    #\"Capitalized Each Word1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isKey": true,
            "lineageTag": "7f316420-9f90-416a-a2d3-f6edc611dcbb",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4081ccd-b993-40df-b3a5-50680bc56975",
            "sourceColumn": "Day Name",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e40be1bc-677c-43d5-8044-c99c063a5f64",
            "sourceColumn": "Start of Week",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "561ffc58-e0e7-41d2-a860-5ca32ca2895e",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "51d279fa-94c0-4e96-8760-a7a956cf8bb8",
            "sourceColumn": "Start of Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f9723dca-cba4-4478-a198-14a321df5d6d",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "30836403-4127-41e7-a345-d9d58c79754d",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "a5833336-b132-4086-b5bb-0540da9aeeee",
            "sourceColumn": "Start of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "201e3fc8-d36b-4dde-82bb-311d3fa3d883",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Number (DAX)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    'Calendar Lookup'[Month Name],",
              "    \"January\", \"1\",",
              "    \"February\", \"2\",",
              "    \"March\", \"3\",",
              "    \"April\", \"4\",",
              "    \"May\", \"5\",",
              "    \"June\", \"6\",",
              "    \"July\", \"7\",",
              "    \"August\", \"8\",",
              "    \"September\", \"9\",",
              "    \"October\", \"10\",",
              "    \"November\", \"11\",",
              "    \"December\", \"12\",",
              "    \"Other\"",
              ")",
              "",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "21b5251e-32e7-4426-8c74-e3c126074757",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "UPPER(",
              "    LEFT(",
              "        'Calendar Lookup'[Month Name],",
              "        3",
              "    )",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "a61a1025-e7ac-4b66-a962-4bee5e599572",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "WEEKDAY(",
              "    'Calendar Lookup'[Date],",
              "    2",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "c9ea5d33-c1b4-4d64-a70d-ba9367e95a9b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Weekend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    'Calendar Lookup'[Day of Week] IN {6,7},",
              "    \"Weekend\",",
              "    \"Weekday\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "6b9fca58-d283-43ac-ba84-148631ea50ad",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "excludeFromModelRefresh": true,
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "levels": [
              {
                "name": "Start of Year",
                "column": "Start of Year",
                "lineageTag": "6a6aef10-f608-463b-8cf7-f9aaea2e5bd1",
                "ordinal": 0
              },
              {
                "name": "Start of Month",
                "column": "Start of Month",
                "lineageTag": "66ca9fda-b547-4f3f-a996-c18e5166c02e",
                "ordinal": 1
              },
              {
                "name": "Start of Week",
                "column": "Start of Week",
                "lineageTag": "384fd303-31fd-4537-a6ca-0de1bb4f88aa",
                "ordinal": 2
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "418681dd-ec2a-4476-8274-db9f6a665289",
                "ordinal": 3
              }
            ],
            "lineageTag": "55dc7c95-73f6-4bac-aa73-15d34e9657c9"
          }
        ],
        "lineageTag": "e120aaff-9838-4a68-bd1e-c2f10342eca3",
        "partitions": [
          {
            "name": "Calendar Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\MicrosoftPowerBIDesktopForBusinessIntelligence\\AdventureWorksRawData\\AdventureWorks Calendar Lookup.csv\"),[Delimiter=\",\", Columns=1, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Date\", type date}}),",
                "    #\"Inserted Day Name\" = Table.AddColumn(#\"Changed Type\", \"Day Name\", each Date.DayOfWeekName([Date]), type text),",
                "    #\"Inserted Start of Week\" = Table.AddColumn(#\"Inserted Day Name\", \"Start of Week\", each Date.StartOfWeek([Date],Day.Monday)),",
                "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Inserted Start of Week\", \"Start of Month\", each Date.StartOfMonth([Date]), type date),",
                "    #\"Inserted Start of Quarter\" = Table.AddColumn(#\"Inserted Start of Month\", \"Start of Quarter\", each Date.StartOfQuarter([Date]), type date),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Inserted Start of Quarter\", \"Month Name\", each Date.MonthName([Date]), type text),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Inserted Month Name\", \"Month\", each Date.Month([Date]), Int64.Type),",
                "    #\"Inserted Start of Year\" = Table.AddColumn(#\"Inserted Month\", \"Start of Year\", each Date.StartOfYear([Date]), type date),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Inserted Start of Year\", \"Year\", each Date.Year([Date]), Int64.Type),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Inserted Year\",{{\"Start of Week\", type date}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales Data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isHidden": true,
            "lineageTag": "b755a038-aa19-466e-a052-bf35c3c8a1cb",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none"
          },
          {
            "name": "StockDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isHidden": true,
            "lineageTag": "c984dd2f-4e5d-4a6d-8561-1e6ef905ca8e",
            "sourceColumn": "StockDate",
            "summarizeBy": "none"
          },
          {
            "name": "OrderNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8ff0a94-9004-43e0-bdcd-cc23c231975f",
            "sourceColumn": "OrderNumber",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "137369dd-be9d-40e1-b271-13b624f99553",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d3185b22-c27d-4321-b52f-8b8125891e23",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "TerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e64090d8-6a74-4a4d-b630-22ac87d588aa",
            "sourceColumn": "TerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "OrderLineItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5a1ab400-358f-41e8-b70a-e2d9ee588eb0",
            "sourceColumn": "OrderLineItem",
            "summarizeBy": "sum"
          },
          {
            "name": "OrderQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9186061c-18d4-4542-90e9-b6f9f0a579ec",
            "sourceColumn": "OrderQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    'Sales Data'[OrderQuantity] > 1,",
              "    \"Multiple Items\",",
              "    \"Single Item\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "16c9c650-9c1b-4d38-aab8-441eaef1ed51",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "f286be88-be15-4791-8a35-ccec82d86cef",
        "partitions": [
          {
            "name": "Sales Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\Pranav Bhoola\\Desktop\\MicrosoftPowerBIDesktopForBusinessIntelligence\\Sales Data\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File\", each #\"Transform File\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File\"(#\"Sample File\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"OrderDate\", type date}, {\"StockDate\", type date}, {\"OrderNumber\", type text}, {\"ProductKey\", Int64.Type}, {\"CustomerKey\", Int64.Type}, {\"TerritoryKey\", Int64.Type}, {\"OrderLineItem\", Int64.Type}, {\"OrderQuantity\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Source.Name\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Returns Data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ReturnDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isHidden": true,
            "lineageTag": "2e01b073-6962-4788-a021-e44bf30f848d",
            "sourceColumn": "ReturnDate",
            "summarizeBy": "none"
          },
          {
            "name": "TerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2da1534a-7199-40f3-b177-4f511a9d8de5",
            "sourceColumn": "TerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4d791bae-9be2-4cbd-820b-4052d3893202",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ReturnQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b2812680-7e38-47f7-a39a-632631a528c6",
            "sourceColumn": "ReturnQuantity",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ccdf5be7-3a69-4382-b44f-f31cb065dab7",
        "partitions": [
          {
            "name": "Returns Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\MicrosoftPowerBIDesktopForBusinessIntelligence\\AdventureWorksRawData\\AdventureWorks Returns Data.csv\"),[Delimiter=\",\", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ReturnDate\", type date}, {\"TerritoryKey\", Int64.Type}, {\"ProductKey\", Int64.Type}, {\"ReturnQuantity\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measure Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "7a8b0f14-c54c-4b28-a5aa-791483f0a683",
        "measures": [
          {
            "name": "Quantity Sold",
            "expression": [
              "",
              "SUM(",
              "    'Sales Data'[OrderQuantity]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "dd358a9f-2e07-4cc3-9709-dac5f9f229f4"
          },
          {
            "name": "Quantity Returned",
            "expression": [
              "",
              " SUM(",
              "    'Returns Data'[ReturnQuantity]",
              " )"
            ],
            "formatString": "0",
            "lineageTag": "649c0b01-9391-44fc-8bd7-999232a7c149"
          },
          {
            "name": "Average Retail Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              "AVERAGE(",
              "    'Product Lookup'[ProductPrice]",
              ")"
            ],
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "be8fc1a0-8faa-4566-be1b-1c26d0cc4d6f"
          },
          {
            "name": "Total Returns",
            "expression": [
              "",
              "COUNT(",
              "    'Returns Data'[ReturnQuantity]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "ee4a27c3-d5dd-467c-bbe3-a7c07eb57ae3"
          },
          {
            "name": "Total Orders",
            "expression": [
              "",
              "DISTINCTCOUNT(",
              "    'Sales Data'[OrderNumber]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "2eac597f-b1af-411d-ac7b-1c8f2709d44a"
          },
          {
            "name": "Total Customers",
            "expression": [
              "",
              "DISTINCTCOUNT(",
              "    'Sales Data'[CustomerKey]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "dc044cab-ef33-44a7-8f29-dda24e872911"
          },
          {
            "name": "Return Rate",
            "expression": [
              "",
              "DIVIDE(",
              " [Quantity Returned],",
              " [Quantity Sold],",
              " \"No Sales\"",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "91e35aa1-6f9d-45cd-8db0-b43e03392830"
          },
          {
            "name": "Bulk Orders",
            "expression": [
              "",
              " CALCULATE(",
              "    [Total Orders],",
              "    'Sales Data'[OrderQuantity] > 1",
              " )"
            ],
            "formatString": "#,0",
            "lineageTag": "9cb48adf-aec7-44e0-82d9-d5e83142e2b3"
          },
          {
            "name": "Weekend Orders",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Orders],",
              "    'Calendar Lookup'[Weekend] = \"Weekend\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "f80d88e7-c0d5-4d91-bf56-f2524fe4fb53"
          },
          {
            "name": "Bike Returns",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Returns],",
              "    'Product Categories Lookup'[CategoryName] = \"Bikes\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "01d34cd3-3002-4d6f-a7d0-893c191b1be1"
          },
          {
            "name": "Bike Sales",
            "expression": [
              "",
              " CALCULATE(",
              "    [Quantity Sold],",
              "    'Product Categories Lookup'[CategoryName] = \"Bikes\"",
              " )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "e266067d-0e39-4147-aa58-34e7348f00e9"
          },
          {
            "name": "Bike Return Rate",
            "expression": [
              "",
              " CALCULATE(",
              "    [Return Rate],",
              "    'Product Categories Lookup'[CategoryName] = \"Bikes\"",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "70658575-63e2-4148-a805-89bb980a5b3f"
          },
          {
            "name": "All Orders",
            "expression": [
              "",
              " CALCULATE(",
              "    [Total Orders],",
              "    ALL(",
              "        'Sales Data'",
              "    )",
              " )"
            ],
            "formatString": "#,0",
            "lineageTag": "b1dcb6ff-561f-49a2-940e-bc0ca7b2bd56"
          },
          {
            "name": "% Of All Orders",
            "expression": [
              "",
              " DIVIDE(",
              "    [Total Orders],",
              "    [All Orders]",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "720ccbe7-3590-40c1-b70e-a0b9ad555ef8"
          },
          {
            "name": "Overall Average Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Average Retail Price],",
              "    ALL(",
              "        'Product Lookup'",
              "    )",
              ")"
            ],
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "5663a4e1-1202-4609-83d2-ea5a8432bd06"
          },
          {
            "name": "All Returns",
            "expression": [
              "",
              " CALCULATE(",
              "    [Total Returns],",
              "    ALL(",
              "        'Returns Data'",
              "    )",
              " )"
            ],
            "formatString": "#,0",
            "lineageTag": "48d0fb24-2eac-4d52-9ffb-a4393f5fda85"
          },
          {
            "name": "% Of All Returns",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Returns],",
              "    [All Returns]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "75450b4b-4257-4c1c-a56c-047b4a0e550b"
          },
          {
            "name": "High Ticket Orders",
            "expression": [
              "",
              " CALCULATE(",
              "    [Total Orders],",
              "    FILTER(",
              "        'Product Lookup',",
              "        'Product Lookup'[ProductPrice] > [Overall Average Price]",
              "    )",
              " )"
            ],
            "formatString": "#,0",
            "lineageTag": "df4f36c7-2a25-4dd9-98a4-9bb2bae3db44"
          },
          {
            "name": "Total Revenue",
            "expression": [
              "",
              "SUMX(",
              "    'Sales Data',",
              "    'Sales Data'[OrderQuantity] *",
              "     RELATED(",
              "        'Product Lookup'[ProductPrice]",
              "     )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "4561881c-ab8e-4013-b934-2e61129a815f"
          },
          {
            "name": "Average Revenue per Customer",
            "expression": [
              "",
              " DIVIDE(",
              "    [Total Revenue],",
              "    [Total Customers]",
              " )"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "73a6aec2-a57a-41e4-976b-a49de37ca292"
          },
          {
            "name": "Total Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              " SUMX(",
              "    'Sales Data',",
              "    'Sales Data'[OrderQuantity] *",
              "    RELATED(",
              "        'Product Lookup'[ProductCost]",
              "    )",
              " )"
            ],
            "formatString": "\"R\"#,0;-\"R\"#,0;\"R\"#,0",
            "lineageTag": "9b264986-24db-408f-9603-8609d4d2205b"
          },
          {
            "name": "Total Profit",
            "expression": [
              "",
              " [Total Revenue] - [Total Cost]"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d14952cd-d260-4226-8a75-e204df6737fc"
          },
          {
            "name": "YTD Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              " CALCULATE(",
              "    [Total Revenue], ",
              "    DATESYTD(",
              "        'Calendar Lookup'[Date]",
              "    )",
              " )"
            ],
            "formatString": "\"R\"#,0;-\"R\"#,0;\"R\"#,0",
            "lineageTag": "e8520cbd-f945-4a84-8f77-de23a8c28da0"
          },
          {
            "name": "Previous Month Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Revenue],",
              "    DATEADD(",
              "        'Calendar Lookup'[Date],",
              "        -1,",
              "        MONTH",
              "    )",
              ")"
            ],
            "formatString": "\"R\"#,0;-\"R\"#,0;\"R\"#,0",
            "lineageTag": "f4dfcabb-5298-4476-90ea-b81c5d461d99"
          },
          {
            "name": "Revenue Target",
            "expression": [
              "",
              " [Previous Month Revenue] * 1.1"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "0181327d-bd40-4d46-b3ec-7f64f7d2e59f"
          },
          {
            "name": "10-Day Rolling Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              " CALCULATE(",
              "    [Total Revenue],",
              "    DATESINPERIOD(",
              "        'Calendar Lookup'[Date],",
              "        MAX(",
              "            'Calendar Lookup'[Date]",
              "        ),",
              "        -10,",
              "        DAY",
              "    )",
              " )"
            ],
            "formatString": "\"R\"#,0;-\"R\"#,0;\"R\"#,0",
            "lineageTag": "91844a40-52a6-44bc-a394-5c6fa65bb336"
          },
          {
            "name": "Previous Month Returns",
            "expression": [
              "",
              " CALCULATE(",
              "    [Total Returns],",
              "    DATEADD(",
              "        'Calendar Lookup'[Date],",
              "        -1,",
              "        MONTH",
              "    )",
              " )"
            ],
            "formatString": "0",
            "lineageTag": "ac312d18-b8d5-4e26-afb6-89e63625d857"
          },
          {
            "name": "Previous Month Orders",
            "expression": [
              "",
              " CALCULATE(",
              "    [Total Orders],",
              "    DATEADD(",
              "        'Calendar Lookup'[Date],",
              "        -1,",
              "        MONTH",
              "    )",
              " )"
            ],
            "formatString": "0",
            "lineageTag": "a3af2dbe-1c97-4577-a562-59e497d8eafe"
          },
          {
            "name": "Previous Month Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              " CALCULATE(",
              "    [Total Profit],",
              "    DATEADD(",
              "        'Calendar Lookup'[Date],",
              "        -1,",
              "        MONTH",
              "    )",
              " )"
            ],
            "formatString": "\"R\"#,0;-\"R\"#,0;\"R\"#,0",
            "lineageTag": "5bb3b8fb-9951-4d79-bf9b-76ca44cf0767"
          },
          {
            "name": "Order Target",
            "expression": [
              "",
              "[Previous Month Orders] * 1.1"
            ],
            "formatString": "#,0",
            "lineageTag": "47ed3d94-e59f-4d79-a2ad-402307957ed9"
          },
          {
            "name": "Profit Target",
            "expression": [
              "",
              "[Previous Month Profit] * 1.1"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "887b7fb1-213c-415e-a929-0907d94edd7d"
          },
          {
            "name": "90-Day Rolling Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              " CALCULATE(",
              "    [Total Profit],",
              "    DATESINPERIOD(",
              "        'Calendar Lookup'[Date],",
              "        MAX(",
              "            'Calendar Lookup'[Date]",
              "        ),",
              "        -90,",
              "        DAY",
              "    )",
              " )"
            ],
            "formatString": "\"R\"#,0;-\"R\"#,0;\"R\"#,0",
            "lineageTag": "1b92d333-49dd-4444-8dfe-f77aa8db5b9a"
          },
          {
            "name": "Total Orders (Customer Detail)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              " IF(",
              "    HASONEVALUE(",
              "        'Customer Lookup'[CustomerKey]",
              "    ),",
              "    [Total Orders],",
              "    \"-\"",
              " )"
            ],
            "formatString": "0",
            "lineageTag": "a3a84796-a561-462d-968e-6f3332cbaa9b"
          },
          {
            "name": "Total Revenue (Customer Detail)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              " IF(",
              "    HASONEVALUE(",
              "        'Customer Lookup'[CustomerKey]",
              "    ),",
              "    [Total Revenue],",
              "    \"-\"",
              " )"
            ],
            "lineageTag": "0d770890-5e08-4e06-b4eb-f5cba93b5349"
          },
          {
            "name": "Order Target Gap",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Total Orders] - [Order Target]",
            "lineageTag": "3d07684b-5379-42cf-a248-66086f52c81a"
          },
          {
            "name": "Revenue Target Gap",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": "[Total Revenue] - [Revenue Target]",
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "88738229-82d1-4833-b4c5-c881e1d5618b"
          },
          {
            "name": "Profit Target Gap",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": "[Total Profit] - [Profit Target]",
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "cc2c30e5-df08-448c-9299-99f685943919"
          },
          {
            "name": "Adjusted Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": "[Average Retail Price] * (1 + 'Price Adjustment (%)'[Price Adjustment (%) Value])",
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "5086ef8d-a7e0-4a2a-8612-846e84915584"
          },
          {
            "name": "Adjusted Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              "SUMX(",
              "    'Sales Data',",
              "    'Sales Data'[OrderQuantity] * [Adjusted Price])"
            ],
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "6afc3432-6ebc-4695-bcba-cb2f7f986d44"
          },
          {
            "name": "Adjusted Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              " [Adjusted Revenue] - [Total Cost]"
            ],
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "7131719f-0821-461e-b690-b2acf2ae2284"
          },
          {
            "name": "Revenue Sparkline",
            "expression": [
              "",
              "// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)",
              "VAR LineColour = \"%23118DFF\"",
              "VAR PointColour = \"white\"",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>",
              "        <stop stop-color='#118DFF' offset='0' />",
              "        <stop stop-color='#118DFF' offset='0.3' />",
              "        <stop stop-color='white' offset='1' />",
              "    </linearGradient>",
              "</defs>\"",
              "// \"Date\" field used in this example along the X axis",
              "VAR XMinDate = MIN('Calendar Lookup'[Start of Month])",
              "VAR XMaxDate = MAX('Calendar Lookup'[Start of Month])",
              "",
              "// Obtain overall min and overall max measure values when evaluated for each date",
              "VAR YMinValue = MINX(Values('Calendar Lookup'[Start of Month]),CALCULATE([Total Revenue]))",
              "VAR YMaxValue = MAXX(Values('Calendar Lookup'[Start of Month]),CALCULATE([Total Revenue]))",
              "",
              "// Build table of X & Y coordinates and fit to 50 x 150 viewbox",
              "VAR SparklineTable = ADDCOLUMNS(",
              "    SUMMARIZE('Calendar Lookup','Calendar Lookup'[Start of Month]),",
              "        \"X\",INT(150 * DIVIDE('Calendar Lookup'[Start of Month] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\",INT(50 * DIVIDE([Total Revenue] - YMinValue,YMaxValue - YMinValue)))",
              "",
              "// Concatenate X & Y coordinates to build the sparkline",
              "VAR Lines = CONCATENATEX(SparklineTable,[X] & \",\" & 50-[Y],\" \", 'Calendar Lookup'[Start of Month])",
              "",
              "// Last data points on the line",
              "VAR LastSparkYValue = MAXX( FILTER(SparklineTable, 'Calendar Lookup'[Start of Month] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX( FILTER(SparklineTable, 'Calendar Lookup'[Start of Month] = XMaxDate), [X])",
              "",
              "// Add to SVG, and verify Data Category is set to Image URL for this measure",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    --- gradient---",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" & Defs & ",
              "     \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' ",
              "      stroke-width='0' points=' 0 50 \" & Lines & ",
              "      \" 150 150 Z '/>\" &",
              "    --- Lines---",
              "    \"<polyline ",
              "        fill='transparent' stroke='\" & LineColour & \"' ",
              "        stroke-linecap='round' stroke-linejoin='round' ",
              "        stroke-width='3' points=' \" & Lines & ",
              "      \" '/>\" &",
              "    --- Last Point---",
              "        \"<circle cx='\"& LastSparkXValue & \"' cy='\" & 50 - LastSparkYValue & \"' r='4' stroke='\" & LineColour & \"' stroke-width='3' fill='\" & PointColour & \"' />\" &",
              "        \"</svg>\"",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "f6162246-11f5-4756-80d9-a93f6706d473"
          },
          {
            "name": "Test",
            "expression": "\"This is a test measure, please delete\"",
            "lineageTag": "08a782d1-31d4-4c8a-b304-e29e4bff0678"
          }
        ],
        "partitions": [
          {
            "name": "Measure Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Price Adjustment (%)",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e5c0fb82bf934ddb85ad201eaa26b609"
          }
        ],
        "columns": [
          {
            "name": "Price Adjustment (%)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "34cdbd54-ec4b-4c6c-b184-37e7a0bc3855",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "df8e24a4-7b9b-4440-b1c0-425d03a14602",
        "measures": [
          {
            "name": "Price Adjustment (%) Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SELECTEDVALUE('Price Adjustment (%)'[Price Adjustment (%)], 0)",
            "lineageTag": "685cf6fc-aa9e-43c6-bc76-46f447db369b"
          }
        ],
        "partitions": [
          {
            "name": "Price Adjustment (%)",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(-1, 1, 0.1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Product Metric Selection",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "069863b9dd5b4269b5af203b7bab1c78"
          }
        ],
        "columns": [
          {
            "name": "Product Metric Selection",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "d22741c1-118f-4012-90e7-b9c78f88ccb8",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Product Metric Selection Fields"
                }
              ]
            },
            "sortByColumn": "Product Metric Selection Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Product Metric Selection Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "cd9c7aa9-1e53-46f0-9609-bc5825d6991c",
            "sortByColumn": "Product Metric Selection Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Product Metric Selection Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "e60ddaaf-50fd-4d7d-b527-e826fca95a77",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "12d2d4ec-bef1-4dbf-a327-2a4eb8b59014",
        "partitions": [
          {
            "name": "Product Metric Selection",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Orders\", NAMEOF('Measure Table'[Total Orders]), 0),",
                "    (\"Revenue\", NAMEOF('Measure Table'[Total Revenue]), 1),",
                "    (\"Profit\", NAMEOF('Measure Table'[Total Profit]), 2),",
                "    (\"Returns\", NAMEOF('Measure Table'[Total Returns]), 3),",
                "    (\"Return %\", NAMEOF('Measure Table'[Return Rate]), 4)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Customer Metric Selection",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "77fc7fb2149e4533a97d07648c5466f6"
          }
        ],
        "columns": [
          {
            "name": "Customer Metric Selection",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "1472c0f2-cda5-45c0-8994-990d40fa5fc5",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Customer Metric Selection Fields"
                }
              ]
            },
            "sortByColumn": "Customer Metric Selection Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Customer Metric Selection Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "205fa853-ee09-4da5-b8df-7c1a88d780cc",
            "sortByColumn": "Customer Metric Selection Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Customer Metric Selection Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "92fafaf8-12d2-4cb3-a691-cfefa21f1b0c",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f6e573b8-62bf-489d-8bff-3c07c81c808b",
        "partitions": [
          {
            "name": "Customer Metric Selection",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Total Customers\", NAMEOF('Measure Table'[Total Customers]), 0),",
                "    (\"Revenue per Customer\", NAMEOF('Measure Table'[Average Revenue per Customer]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}