{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0 (24.06)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Calendar\",\"Customer Lookup\",\"Employee Lookup\",\"Food Inventory\",\"Product Lookup\",\"Sales by Store\",\"Store Lookup\",\"Measure Table\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "d37fe5d8-4cab-0049-00d9-527c2a2baebe",
        "fromColumn": "transaction_date",
        "fromTable": "Sales by Store",
        "toColumn": "Transaction_Date",
        "toTable": "Calendar"
      },
      {
        "name": "5e1b4318-540d-301b-8b7c-3997bd11d3e1",
        "fromColumn": "transaction_date",
        "fromTable": "Food Inventory",
        "toColumn": "Transaction_Date",
        "toTable": "Calendar"
      },
      {
        "name": "d1747f96-03b0-fc4c-1943-cdd0470732e5",
        "fromColumn": "customer_id",
        "fromTable": "Sales by Store",
        "toColumn": "customer_id",
        "toTable": "Customer Lookup"
      },
      {
        "name": "7d8e715f-af22-56c5-20f3-eb551fb06523",
        "fromColumn": "staff_id",
        "fromTable": "Sales by Store",
        "toColumn": "staff_id",
        "toTable": "Employee Lookup"
      },
      {
        "name": "a6d432b7-0a54-5f95-4c85-66b60d717c48",
        "fromColumn": "product_id",
        "fromTable": "Sales by Store",
        "toColumn": "product_id",
        "toTable": "Product Lookup"
      },
      {
        "name": "c3fa5486-f3b5-6bb4-a1eb-87e397655365",
        "fromColumn": "product_id",
        "fromTable": "Food Inventory",
        "toColumn": "product_id",
        "toTable": "Product Lookup"
      },
      {
        "name": "d13f4530-d680-87b3-a107-f8a8c9caab9d",
        "fromColumn": "store_id",
        "fromTable": "Sales by Store",
        "toColumn": "store_id",
        "toTable": "Store Lookup"
      },
      {
        "name": "dae4ee31-5f56-ec97-e7e2-2d742eb9601e",
        "fromColumn": "store_id",
        "fromTable": "Food Inventory",
        "toColumn": "store_id",
        "toTable": "Store Lookup"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Transaction_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "d8f53849-0bff-4903-9934-68e72903f74b",
            "sourceColumn": "Transaction_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Date_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "789d7595-590d-42f6-96cc-975b5ca61c76",
            "sourceColumn": "Date_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Week_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "34f11a37-f221-4a5d-9777-5f339113c453",
            "sourceColumn": "Week_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Week_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a08dd0d1-0f85-474f-9e96-ce8dee5c626f",
            "sourceColumn": "Week_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "Month_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "645c42ba-8e7c-4585-ae82-5ca75bc8c89c",
            "sourceColumn": "Month_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Month_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93406ad2-edd0-474b-a954-f3a90f2ff1d2",
            "sourceColumn": "Month_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c4339148-efc5-4cba-8a83-9e1f22fbd829",
            "sourceColumn": "Quarter_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Quarter_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "271e0728-a977-4b04-9f85-6b981f1e3008",
            "sourceColumn": "Quarter_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Year_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "316ecff3-1563-4458-b3e9-8391e5bbf706",
            "sourceColumn": "Year_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Week_Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87ff53a0-6df8-41fc-936b-0ba9836e0a3c",
            "sourceColumn": "Week_Year",
            "summarizeBy": "none"
          },
          {
            "name": "ISNUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": [
              "",
              "ISTEXT('Calendar'[Week_Desc])"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "lineageTag": "95640a9e-9ada-43b6-879e-13229648a9dc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date Format (yyyy-mm-dd)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "FORMAT(",
              "    'Calendar'[Transaction_Date],",
              "    \"yyyy-mm-dd\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "6804b28e-496a-4f02-ac31-d3721dcc5fa8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year Half",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    'Calendar'[Month_ID],",
              "    1, \"1H\",",
              "    2, \"1H\",",
              "    3, \"1H\",",
              "    4, \"1H\",",
              "    5, \"1H\",",
              "    6, \"1H\",",
              "    7, \"2H\",",
              "    8, \"2H\",",
              "    9, \"2H\",",
              "    10, \"2H\",",
              "    11, \"2H\",",
              "    12, \"2H\",",
              "    \"-\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "eabfde4a-6b68-4ac7-96f8-493e40c4b97a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter & Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              " VAR Q1 = 'Calendar'[Month_ID] IN {1,2,3}",
              " VAR Q2 = 'Calendar'[Month_ID] IN {4,5,6}",
              " VAR Q3 = 'Calendar'[Month_ID] IN {7,8,9}",
              " VAR Q4 = 'Calendar'[Month_ID] IN {10,11,12}",
              "",
              " RETURN",
              " SWITCH(",
              "    TRUE(),",
              "    Q1,\"Q1\" & \"-\" & 'Calendar'[Year_ID],",
              "    Q2,\"Q2\" & \"-\" & 'Calendar'[Year_ID],",
              "    Q3,\"Q3\" & \"-\" & 'Calendar'[Year_ID],",
              "    Q4,\"Q4\" & \"-\" & 'Calendar'[Year_ID],",
              "    \"-\"",
              " )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "59146ef2-9255-43a7-9c6c-2bfdd9704da8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "135c37ae-a73a-4a30-95ca-041868cdd453",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\AdvancedDAX\\AdvancedDAXDataFiles\\Calendar.csv\"),[Delimiter=\",\", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Transaction_Date\", type date}, {\"Date_ID\", Int64.Type}, {\"Week_ID\", Int64.Type}, {\"Week_Desc\", type text}, {\"Month_ID\", Int64.Type}, {\"Month_Name\", type text}, {\"Quarter_ID\", Int64.Type}, {\"Quarter_Name\", type text}, {\"Year_ID\", Int64.Type}, {\"Week_Year\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9acf8c92-5214-43d9-972d-70547705429f",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "home_store",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4ef27497-0838-4402-aaf5-dedade04dd83",
            "sourceColumn": "home_store",
            "summarizeBy": "none"
          },
          {
            "name": "customer_first-name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9ee9d78-8cba-429a-ab53-fc6168cb71c5",
            "sourceColumn": "customer_first-name",
            "summarizeBy": "none"
          },
          {
            "name": "customer_email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffab9da8-c6be-4d07-98f3-f10e91967d50",
            "sourceColumn": "customer_email",
            "summarizeBy": "none"
          },
          {
            "name": "customer_since",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8f98a7da-216f-4a8a-b113-ef1a8d606f91",
            "sourceColumn": "customer_since",
            "summarizeBy": "none"
          },
          {
            "name": "loyalty_card_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11ab843f-3b3f-4b88-b48a-afe6fa382b31",
            "sourceColumn": "loyalty_card_number",
            "summarizeBy": "none"
          },
          {
            "name": "birthdate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "338d26af-5f4e-4216-ae2f-13dad066faf7",
            "sourceColumn": "birthdate",
            "summarizeBy": "none"
          },
          {
            "name": "gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14e19702-78a7-4079-929a-05066e14a9b0",
            "sourceColumn": "gender",
            "summarizeBy": "none"
          },
          {
            "name": "birth_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d2ca16c0-f162-46dc-b89f-690fa93c65ee",
            "sourceColumn": "birth_year",
            "summarizeBy": "none"
          },
          {
            "name": "Current Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "FLOOR(",
              "    DATEDIFF(",
              "        'Customer Lookup'[birthdate],",
              "        TODAY(),",
              "        DAY",
              "    )/365.25,",
              "    1",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "82c46fe4-77c1-471e-8dc7-07fba8699da6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "8342908d-eaca-454a-94ef-fc72763293bc",
        "partitions": [
          {
            "name": "Customer Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\AdvancedDAX\\AdvancedDAXDataFiles\\Customer Lookup.csv\"),[Delimiter=\",\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"customer_id\", Int64.Type}, {\"home_store\", Int64.Type}, {\"customer_first-name\", type text}, {\"customer_email\", type text}, {\"customer_since\", type date}, {\"loyalty_card_number\", type text}, {\"birthdate\", type date}, {\"gender\", type text}, {\"birth_year\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Employee Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "staff_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "846809bb-5933-46ba-8738-f05b36db0eb5",
            "sourceColumn": "staff_id",
            "summarizeBy": "none"
          },
          {
            "name": "first_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6b30f95-82f0-4853-b559-1c150aad2ae8",
            "sourceColumn": "first_name",
            "summarizeBy": "none"
          },
          {
            "name": "last_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2597739-bbf2-49b9-94c2-ad1e54a054ea",
            "sourceColumn": "last_name",
            "summarizeBy": "none"
          },
          {
            "name": "position",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "124b483d-1a07-415a-ab03-cdbdea8ed1a8",
            "sourceColumn": "position",
            "summarizeBy": "none"
          },
          {
            "name": "start_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8b80c396-b2eb-4e5c-a346-5cbd5b5209a7",
            "sourceColumn": "start_date",
            "summarizeBy": "none"
          },
          {
            "name": "location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12c4930f-47e7-4767-bd21-f2a24f3b087d",
            "sourceColumn": "location",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b275e41a-310f-49ed-97d5-11ecabedc8cc",
        "partitions": [
          {
            "name": "Employee Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\AdvancedDAX\\AdvancedDAXDataFiles\\Employee Lookup.csv\"),[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"staff_id\", Int64.Type}, {\"first_name\", type text}, {\"last_name\", type text}, {\"position\", type text}, {\"start_date\", type date}, {\"location\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Food Inventory",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "store_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d3613500-ede6-42d9-aae9-a1c94375e506",
            "sourceColumn": "store_id",
            "summarizeBy": "none"
          },
          {
            "name": "baked_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "66c2deb4-f2be-4918-9473-5fe6c3f6ab0e",
            "sourceColumn": "baked_date",
            "summarizeBy": "none"
          },
          {
            "name": "transaction_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "48332005-0761-4c52-b3f7-82ff20be136e",
            "sourceColumn": "transaction_date",
            "summarizeBy": "none"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3d7d51ae-2616-45fc-aabb-764a45dbb04e",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "quantity_start_of_day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1d1856cb-bd08-4d2b-92bc-bd6041b5ac7f",
            "sourceColumn": "quantity_start_of_day",
            "summarizeBy": "sum"
          },
          {
            "name": "quantity_sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f2304a0a-1b64-4362-80f6-c006549ace75",
            "sourceColumn": "quantity_sold",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity Sold (SUM)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "SUM(",
              "    'Food Inventory'[quantity_sold]",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "da5ef5a2-c60a-4bd6-8788-8fe3a0d7e4e8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Quantity Sold (CALCULATE)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(",
              "        'Food Inventory'[quantity_sold]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "9feac42c-16e1-4e65-9f12-a0884c8f085b",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "adfff7d6-4a32-43e3-9d5e-1d75176ebab3",
        "partitions": [
          {
            "name": "Food Inventory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\AdvancedDAX\\AdvancedDAXDataFiles\\Food Inventory.csv\"),[Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"store_id\", Int64.Type}, {\"baked_date\", type date}, {\"transaction_date\", type date}, {\"product_id\", Int64.Type}, {\"quantity_start_of_day\", Int64.Type}, {\"quantity_sold\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d7ccd02d-ae65-4e4c-b4f9-ad5f2a0f8b02",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "product_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecdd7f93-d057-402a-9615-c6e531c844f3",
            "sourceColumn": "product_group",
            "summarizeBy": "none"
          },
          {
            "name": "product_category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ccf92288-fd8e-4579-b156-7ece997d6359",
            "sourceColumn": "product_category",
            "summarizeBy": "none"
          },
          {
            "name": "product_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5008cc20-b8c7-4690-97bb-883f57f031e1",
            "sourceColumn": "product_type",
            "summarizeBy": "none"
          },
          {
            "name": "product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "913eef0c-65d1-4f04-b011-6dfb0c14f1f8",
            "sourceColumn": "product",
            "summarizeBy": "none"
          },
          {
            "name": "product_description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46d22ffd-b779-4485-8b16-1704abd48aa4",
            "sourceColumn": "product_description",
            "summarizeBy": "none"
          },
          {
            "name": "unit_of_measure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c67fdfc7-9f40-4b1d-bc6e-23124931367c",
            "sourceColumn": "unit_of_measure",
            "summarizeBy": "none"
          },
          {
            "name": "current_cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a42fc65c-dd17-48e4-8835-01af62df470d",
            "sourceColumn": "current_cost",
            "summarizeBy": "sum"
          },
          {
            "name": "current_wholesale_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d1c89d60-bfa1-4c4e-b16b-e6008d960279",
            "sourceColumn": "current_wholesale_price",
            "summarizeBy": "sum"
          },
          {
            "name": "current_retail_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6378d5b5-2904-4c19-bfac-e6ddb51005c8",
            "sourceColumn": "current_retail_price",
            "summarizeBy": "sum"
          },
          {
            "name": "tax_exempt_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a69eeb3d-efd9-4e5b-8188-5b524438e556",
            "sourceColumn": "tax_exempt_yn",
            "summarizeBy": "none"
          },
          {
            "name": "promo_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2ac483a-ba16-4449-9d1d-9bbb9f3fc2d9",
            "sourceColumn": "promo_yn",
            "summarizeBy": "none"
          },
          {
            "name": "new_product_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "901f4f27-be6e-403a-b7c6-5ebb579bf619",
            "sourceColumn": "new_product_yn",
            "summarizeBy": "none"
          },
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d644a9ef-b987-4e5c-88ae-490ae6cc11b0",
            "sourceColumn": "Column1",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "2e087087-5d16-44a1-a2ab-e98b69c56132",
        "partitions": [
          {
            "name": "Product Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\AdvancedDAX\\AdvancedDAXDataFiles\\Product Lookup (Updated).csv\"),[Delimiter=\",\", Columns=14, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"product_id\", Int64.Type}, {\"product_group\", type text}, {\"product_category\", type text}, {\"product_type\", type text}, {\"product\", type text}, {\"product_description\", type text}, {\"unit_of_measure\", type text}, {\"current_cost\", type number}, {\"current_wholesale_price\", type number}, {\"current_retail_price\", type number}, {\"tax_exempt_yn\", type text}, {\"promo_yn\", type text}, {\"new_product_yn\", type text}, {\"\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales by Store",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "transaction_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "719db40f-9f3e-436f-a820-35df66db43f1",
            "sourceColumn": "transaction_id",
            "summarizeBy": "sum"
          },
          {
            "name": "transaction_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e2d3e7a7-671d-42fc-9935-b38c5c4e5f86",
            "sourceColumn": "transaction_date",
            "summarizeBy": "none"
          },
          {
            "name": "transaction_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "hh:nn:ss",
            "lineageTag": "cf58c306-11ee-4c6c-9699-122abf08d5c2",
            "sourceColumn": "transaction_time",
            "summarizeBy": "none"
          },
          {
            "name": "store_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e04c7e78-a9f7-4a80-bdba-c1a993418824",
            "sourceColumn": "store_id",
            "summarizeBy": "none"
          },
          {
            "name": "staff_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9f2b3df9-c153-4fc2-ae79-311840257b35",
            "sourceColumn": "staff_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c19d9559-a84c-4322-ab64-dc3f382d73e0",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "instore_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30c784c6-bc26-4960-bbb2-c16f685b62a7",
            "sourceColumn": "instore_yn",
            "summarizeBy": "none"
          },
          {
            "name": "order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "640084ca-74c5-4379-b49f-d15d4736265d",
            "sourceColumn": "order",
            "summarizeBy": "sum"
          },
          {
            "name": "line_item_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e295ad65-f811-419b-9169-5f44628af132",
            "sourceColumn": "line_item_id",
            "summarizeBy": "sum"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "df8c2921-9ba9-41f6-82cc-d2b95a8cd721",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "quantity_sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5e267f3a-0130-49a4-bc95-f55d5272f586",
            "sourceColumn": "quantity_sold",
            "summarizeBy": "sum"
          },
          {
            "name": "unit_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "563a20a4-3db5-46e2-8703-1119d47bf58d",
            "sourceColumn": "unit_price",
            "summarizeBy": "sum"
          },
          {
            "name": "promo_item_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85a5a641-ec14-435d-ade2-0b746a511c13",
            "sourceColumn": "promo_item_yn",
            "summarizeBy": "none"
          },
          {
            "name": "Time Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "FLOOR(",
              "    'Sales by Store'[transaction_time],",
              "    \"1:00\"",
              ")"
            ],
            "formatString": "Long Time",
            "lineageTag": "db95b458-214a-4238-9134-8b2c9a962cf1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Total Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "expression": [
              "",
              "CURRENCY(",
              "    'Sales by Store'[quantity_sold] * 'Sales by Store'[unit_price]",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "17225a84-2c57-4d64-97ad-1e588b5c85ab",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "c9e89f13-5140-4b2f-ad4b-9f2470d801ba",
        "partitions": [
          {
            "name": "Sales by Store",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\AdvancedDAX\\AdvancedDAXDataFiles\\Sales by Store.csv\"),[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"transaction_id\", Int64.Type}, {\"transaction_date\", type date}, {\"transaction_time\", type time}, {\"store_id\", Int64.Type}, {\"staff_id\", Int64.Type}, {\"customer_id\", Int64.Type}, {\"instore_yn\", type text}, {\"order\", Int64.Type}, {\"line_item_id\", Int64.Type}, {\"product_id\", Int64.Type}, {\"quantity_sold\", Int64.Type}, {\"unit_price\", type number}, {\"promo_item_yn\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Store Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "store_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "00684956-e648-49c7-bce1-5a9584c7a8c2",
            "sourceColumn": "store_id",
            "summarizeBy": "none"
          },
          {
            "name": "store_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5dce532-11ad-4755-9c7e-d64e7ed7a1f8",
            "sourceColumn": "store_type",
            "summarizeBy": "none"
          },
          {
            "name": "store_square_feet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1d4d73f6-0c0b-4438-a69d-e277327dc983",
            "sourceColumn": "store_square_feet",
            "summarizeBy": "sum"
          },
          {
            "name": "store_address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bdf54823-0f5f-48a1-a94e-7140e4658fac",
            "sourceColumn": "store_address",
            "summarizeBy": "none"
          },
          {
            "name": "store_city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed0eece0-29a6-469e-ad7e-152e1b09b5d7",
            "sourceColumn": "store_city",
            "summarizeBy": "none"
          },
          {
            "name": "store_state_province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc80a795-eb78-4cd0-9f18-60b19eda8e03",
            "sourceColumn": "store_state_province",
            "summarizeBy": "none"
          },
          {
            "name": "store_postal_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6341930c-ccac-4b4d-ac10-50df162e4b7d",
            "sourceColumn": "store_postal_code",
            "summarizeBy": "sum"
          },
          {
            "name": "store_longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "84b9c723-d1c6-415a-9ecb-ba550f91e95b",
            "sourceColumn": "store_longitude",
            "summarizeBy": "sum"
          },
          {
            "name": "store_latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cc287cd4-8606-4aac-a46b-3ad81fcf4048",
            "sourceColumn": "store_latitude",
            "summarizeBy": "sum"
          },
          {
            "name": "manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8a448887-82c6-4241-9cd3-0cc1310d169a",
            "sourceColumn": "manager",
            "summarizeBy": "sum"
          },
          {
            "name": "Neighorhood",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7667abf1-0131-44e7-b663-5a584f5c0458",
            "sourceColumn": "Neighorhood",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7dea3a8a-9d1e-45c2-9ce1-a190cca46dbe",
        "partitions": [
          {
            "name": "Store Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\AdvancedDAX\\AdvancedDAXDataFiles\\Store Lookup.csv\"),[Delimiter=\",\", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"store_id\", Int64.Type}, {\"store_type\", type text}, {\"store_square_feet\", Int64.Type}, {\"store_address\", type text}, {\"store_city\", type text}, {\"store_state_province\", type text}, {\"store_postal_code\", Int64.Type}, {\"store_longitude\", type number}, {\"store_latitude\", type number}, {\"manager\", Int64.Type}, {\"Neighorhood\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measure Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "1fbbe49d-603a-41d9-98bc-61faabeb9c3e",
        "measures": [
          {
            "name": "Cost",
            "displayFolder": "Tips & Best Practices",
            "expression": [
              "",
              "SUMX(",
              "    'Sales by Store',                   -- Returns the Sales by Store table to ",
              "    'Sales by Store'[quantity_sold] *   -- Evaluate expression sold times cost from a related table ",
              "    RELATED(",
              "        'Product Lookup'[current_cost]",
              "    )",
              ")",
              ""
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "1ce7b783-56ee-4ba9-9941-db4f1f980b33"
          },
          {
            "name": "Customer Sales",
            "displayFolder": "Tips & Best Practices",
            "expression": [
              "",
              "SUMX(",
              "    'Sales by Store', ",
              "    'Sales by Store'[quantity_sold] * 'Sales by Store'[unit_price]",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "1e775394-3774-47e5-8d4f-5a79dcf489fa"
          },
          {
            "name": "Profit",
            "displayFolder": "Tips & Best Practices",
            "expression": [
              "",
              "[Customer Sales] - [Cost]"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "b9811985-9e25-4c0b-86dd-8fd2ff322e7f"
          },
          {
            "name": "Customer Sales (Last Year)",
            "displayFolder": "Tips & Best Practices",
            "expression": [
              "",
              " CALCULATE(",
              "    [Customer Sales],",
              "    DATEADD(",
              "        'Calendar'[Transaction_Date],",
              "        -1, ",
              "        YEAR",
              "    )",
              " )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "7a8f2428-5b83-4a83-8bd1-7887ce0875cf"
          },
          {
            "name": "Customer Sales LY (ISBLANK)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Tips & Best Practices",
            "expression": [
              "",
              "IF(",
              "    ISBLANK(",
              "        [Customer Sales (Last Year)]",
              "    ),",
              "    \"No Sales\",",
              "    [Customer Sales (Last Year)]",
              ")"
            ],
            "lineageTag": "da76d839-88d9-4842-9b34-e814d745ccc6"
          },
          {
            "name": "% Quantity Sold to Females",
            "displayFolder": "Tips & Best Practices",
            "expression": [
              "",
              "VAR TotalOrders_Female = ",
              "CALCULATE(",
              "    SUM(",
              "        'Sales by Store'[quantity_sold]",
              "    ),",
              "    FILTER(",
              "        'Customer Lookup',",
              "        'Customer Lookup'[gender] = \"F\"",
              "    )",
              ")",
              "VAR QuantitySold =",
              "SUM(",
              "    'Sales by Store'[quantity_sold]",
              ")",
              "VAR Ratio = ",
              "DIVIDE(",
              "    TotalOrders_Female,",
              "    QuantitySold,",
              "    \"-\"",
              ")",
              "RETURN",
              "Ratio"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e464e672-257f-4542-9947-2fa8b2fcf75c"
          },
          {
            "name": "Orders by Females (Wrong)",
            "displayFolder": "Tips & Best Practices",
            "expression": [
              "",
              "VAR TotalOrder =",
              "SUM(",
              "    'Sales by Store'[quantity_sold]",
              ")",
              "RETURN",
              "CALCULATE(",
              "    TotalOrder,",
              "    FILTER(",
              "        'Customer Lookup',",
              "        'Customer Lookup'[gender] =\"F\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "2b764be2-99f5-4100-8232-4e45214e6e71"
          },
          {
            "name": "Total Customers",
            "displayFolder": "Scalar Measures",
            "expression": [
              "",
              "DISTINCTCOUNT(",
              "    'Customer Lookup'[customer_id]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "2fe56cf2-0a95-4238-87c2-cb396d8eb223"
          },
          {
            "name": "Total Employees",
            "displayFolder": "Scalar Measures",
            "expression": [
              "",
              " COUNTROWS(",
              "    'Employee Lookup'",
              " )"
            ],
            "formatString": "#,0",
            "lineageTag": "305bcaf3-8762-455a-8040-d2ac231f8e2f"
          },
          {
            "name": "Cost (Currency)",
            "displayFolder": "Scalar Measures",
            "expression": [
              "",
              "ROUND(",
              "    CURRENCY([Cost])",
              "    ,2",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "5342fccb-b7b7-4751-8dbb-9ddb07a91a1f"
          },
          {
            "name": "Customer Sales LY (COALESCE)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Scalar Measures",
            "expression": [
              "",
              "VAR Customer_Sales_LY =",
              " CALCULATE(",
              "    [Customer Sales],",
              "    DATEADD(",
              "        'Calendar'[Transaction_Date],",
              "        -1, ",
              "        YEAR",
              "    )",
              " )",
              " RETURN",
              " COALESCE(",
              "    Customer_Sales_LY,",
              "    \"-\"",
              " )"
            ],
            "lineageTag": "97156cc1-9758-4fff-ab18-05af36aaf690"
          },
          {
            "name": "SUM Quantity Sold",
            "displayFolder": "Advanced CALCULATE",
            "expression": [
              "",
              "SUM(",
              "    'Food Inventory'[quantity_sold]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "79d056e8-6ab5-4d7a-b9ee-800ba900fa58"
          },
          {
            "name": "Calculate SUM Quantity Sold",
            "displayFolder": "Advanced CALCULATE",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(",
              "        'Food Inventory'[quantity_sold]",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "d9583b4f-9790-4514-ada5-85ab24cbbcab"
          },
          {
            "name": "Store 3 Sales of Whole Beans & Teas (CALCULATE)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Advanced CALCULATE",
            "expression": [
              "",
              "CALCULATE(",
              "    [Customer Sales],",
              "    'Store Lookup'[store_id] = 3,",
              "    'Product Lookup'[product_group] = \"Whole Bean/Teas\"",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "3844ece2-a264-4d11-b9b5-aeefac2fb32e"
          },
          {
            "name": "Store 3 Sales of Whole Beans & Teas (ALL MODIFIER)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Advanced CALCULATE",
            "expression": [
              "",
              "CALCULATE(",
              "    [Customer Sales],",
              "    'Store Lookup'[store_id] = 3,",
              "    'Product Lookup'[product_group] = \"Whole Bean/Teas\",",
              "    ALL(",
              "        'Store Lookup'",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "33495de6-1ecd-43e2-a66d-7d2bdf52b0ef"
          },
          {
            "name": "Total Profit",
            "displayFolder": "Advanced CALCULATE",
            "expression": [
              "",
              "CALCULATE(",
              "    [Profit],",
              "    REMOVEFILTERS(",
              "        'Sales by Store'",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "d5d5e89e-c86a-49b6-852a-d96a673f459c"
          },
          {
            "name": "Store 5 Profit (KEEPFILTERS)",
            "displayFolder": "Advanced CALCULATE",
            "expression": [
              "",
              " CALCULATE(",
              "    [Profit],",
              "    KEEPFILTERS(",
              "        'Store Lookup'[store_id] = 5",
              "    )",
              " )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "ac06baf9-4a3c-482f-8cb8-575c668387a8"
          },
          {
            "name": "Store 5 Profit",
            "displayFolder": "Advanced CALCULATE",
            "expression": [
              "",
              " CALCULATE(",
              "    [Profit],",
              "    'Store Lookup'[store_id] = 5",
              " )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "c6fc0727-e36b-4d1e-a19d-14924b5c3833"
          },
          {
            "name": "Store 3 Sales (KEEPFILTERS)",
            "displayFolder": "Advanced CALCULATE",
            "expression": [
              "",
              " CALCULATE(",
              "    [Customer Sales],",
              "    KEEPFILTERS(",
              "        'Store Lookup'[store_id] = 3",
              "    )",
              " )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "9512e3ae-c960-4705-a521-a63e6aa1127e"
          },
          {
            "name": "Store 5 Sales (KEEPFILTERS)",
            "displayFolder": "Advanced CALCULATE",
            "expression": [
              "",
              " CALCULATE(",
              "    [Customer Sales],",
              "    KEEPFILTERS(",
              "        'Store Lookup'[store_id] = 5",
              "    )",
              " )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "9bdf3675-a2ec-4c80-b614-5fbf71c85ac8"
          },
          {
            "name": "Store 8 Sales (KEEPFILTERS)",
            "displayFolder": "Advanced CALCULATE",
            "expression": [
              "",
              " CALCULATE(",
              "    [Customer Sales],",
              "    KEEPFILTERS(",
              "        'Store Lookup'[store_id] = 8",
              "    )",
              " )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "a7033cab-7e78-40f1-b6f2-2aaa0a6c53f9"
          },
          {
            "name": "% of Store Sales (REMOVEFILTERS)",
            "displayFolder": "Advanced CALCULATE",
            "expression": [
              "",
              "VAR AllStoreSales = ",
              "CALCULATE(",
              "    [Customer Sales],",
              "    REMOVEFILTERS(",
              "        'Store Lookup'[store_id]",
              "    )",
              ")",
              "VAR Ratio = ",
              "DIVIDE(",
              "    [Customer Sales],",
              "    AllStoreSales",
              ")",
              "RETURN",
              "Ratio"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "57cfcc88-9a57-4e37-9cad-3a162de129fa"
          },
          {
            "name": "Count of Product ID (DISTINCT)",
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              " COUNTROWS(",
              "    DISTINCT(",
              "        'Product Lookup'[product_id]",
              "    )",
              " )"
            ],
            "formatString": "0",
            "lineageTag": "4b39e695-f714-43bf-bae0-f72c2f1b6bfa"
          },
          {
            "name": "Count of Product ID (VALUES)",
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              " COUNTROWS(",
              "    VALUES(",
              "        'Product Lookup'[product_id]",
              "    )",
              " )"
            ],
            "formatString": "0",
            "lineageTag": "5b835c7c-1101-4060-8cb0-f93b0ee4e46f"
          },
          {
            "name": "Retail Price (SELECTEDVALUE)",
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              "SELECTEDVALUE(",
              "    'Product Lookup'[current_retail_price]",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "0002a1ab-9d4a-47d7-9b23-0e0a44897744"
          },
          {
            "name": "Quantity Sold (SELECTEDVALUE)",
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              "DIVIDE(",
              "    [Customer Sales],",
              "    SELECTEDVALUE(",
              "        'Product Lookup'[current_retail_price]",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "54f50373-ab6d-4dbd-8cf4-2d420d1d21b3"
          },
          {
            "name": "Customer Sales (ALLEXCEPT)",
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              "CALCULATE(",
              "    [Customer Sales],",
              "    ALLEXCEPT(",
              "        'Sales by Store',",
              "        'Product Lookup'[product_group],",
              "        'Calendar'[Transaction_Date]",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "c8e73d65-8f1c-4984-b5c1-7c17a45c7847"
          },
          {
            "name": "Customer Sales (ALLEXCEPT Assignment)",
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              " CALCULATE(",
              "    [Customer Sales],",
              "    ALLEXCEPT(",
              "        'Sales by Store',",
              "        'Calendar'[Transaction_Date],",
              "        'Store Lookup'[store_id],",
              "        'Customer Lookup'[customer_first-name],",
              "        'Product Lookup'[product_group]",
              "    )",
              " )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "4341b098-1764-4c5f-a280-ed617afb3fe8"
          },
          {
            "name": "% of Store-Level Sales",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              "VAR StoreLevelSales = ",
              "CALCULATE(",
              "    [Customer Sales],",
              "    REMOVEFILTERS(",
              "        'Customer Lookup'",
              "    ),",
              "    KEEPFILTERS(",
              "        'Calendar'",
              "    )",
              ")",
              "VAR Ratio = ",
              "DIVIDE(",
              "    [Customer Sales (ALLEXCEPT Assignment)],",
              "    StoreLevelSales",
              ")",
              "RETURN",
              "Ratio"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b1c7b801-e473-4960-94a8-be57365d1670"
          },
          {
            "name": "Customer Sales (ALLSELECTED)",
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              "CALCULATE(",
              "    [Customer Sales],",
              "    ALLSELECTED(",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "7864ee4a-2633-461b-8813-7442f3276a20"
          },
          {
            "name": "Total Baked",
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              "SUMX(",
              "    'Food Inventory',",
              "    'Food Inventory'[quantity_start_of_day]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "2a5ad8be-37f0-495d-b723-c1df45006795"
          },
          {
            "name": "Total Sold",
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              " SUMX(",
              "    'Food Inventory',",
              "    'Food Inventory'[quantity_sold]",
              " )"
            ],
            "formatString": "#,0",
            "lineageTag": "a608519d-cac9-462f-bf50-e4355b47e9bc"
          },
          {
            "name": "% of Total Baked (ALLSELECTED)",
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              "VAR SelectedQuantityBaked = ",
              "CALCULATE(",
              "    [Total Baked],",
              "    ALLSELECTED(",
              "    )",
              ")",
              "VAR Ratio = ",
              "DIVIDE(",
              "    [Total Baked],",
              "    SelectedQuantityBaked,",
              "    \"0\"",
              ")",
              "RETURN",
              "Ratio"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cced01bf-6862-4adf-8335-f2118dba1aef"
          },
          {
            "name": "% of Total Sold (ALLSELECTED)",
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              "VAR SelectedQuantitySold = ",
              "CALCULATE(",
              "    [Total Sold],",
              "    ALLSELECTED(",
              "    )",
              ")",
              "VAR Ratio = ",
              "DIVIDE(",
              "    [Total Sold],",
              "    SelectedQuantitySold,",
              "    \"0\"",
              ")",
              "RETURN",
              "Ratio"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "54550a32-571c-43d5-8e5c-47301e061826"
          },
          {
            "name": "% of All Baked",
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              " VAR AllBaked = ",
              " CALCULATE(",
              "    [Total Baked],",
              "    REMOVEFILTERS(",
              "        'Food Inventory'",
              "    )",
              " )",
              " VAR Ratio = ",
              " DIVIDE(",
              "    [Total Baked],",
              "    AllBaked,",
              "    \"0\"",
              " )",
              " RETURN",
              " Ratio"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e3f9bdad-aba7-44b2-9c26-f8f0b0572e93"
          },
          {
            "name": "Food Sold (SUMMARIZE Table)",
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              " SUM(",
              "    'Unsold Pastries'[quantity_sold]",
              " )"
            ],
            "formatString": "#,0",
            "lineageTag": "9a0c5b73-8a8c-493b-b24e-cf94ee8b3c27"
          },
          {
            "name": "Food Unsold (SUMMARIZE Table)",
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              " SUMX(",
              "    'Unsold Pastries',",
              "    'Unsold Pastries'[quantity_start_of_day] - 'Unsold Pastries'[quantity_sold]",
              " )"
            ],
            "formatString": "#,0",
            "lineageTag": "09d7c2a0-c185-4083-9a78-c15bb3787a54"
          },
          {
            "name": "Lost Revenue (SUMMARIZE Table)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Table & Filter Functions",
            "expression": [
              "",
              " SUMX(",
              "    'Unsold Pastries',",
              "    [Food Sold (SUMMARIZE Table)] * 'Unsold Pastries'[current_retail_price]",
              " )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "87ba89fb-a142-4fbd-94c7-ddabca59969a"
          }
        ],
        "partitions": [
          {
            "name": "Measure Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCk7MLchJVYqNBQA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Values Example",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "42a8589346cb4882812d720f4369ad93"
          }
        ],
        "columns": [
          {
            "name": "product_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e827581a-68d6-4efa-8d0d-fc714b73539f",
            "sourceColumn": "Product Lookup[product_group]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "b576d973-2656-4d94-a1de-261830ba69d3",
        "partitions": [
          {
            "name": "Values Example",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VALUES(",
                "    'Product Lookup'[product_group]",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ADDCOLUMNS Demo",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c444fbdad062475c89f2ad2adad1783a"
          }
        ],
        "columns": [
          {
            "name": "Manager Name & Store",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d708c25e-8533-4b40-a9ad-56caab81d14a",
            "sourceColumn": "[Manager Name & Store]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "staff_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f8a353e0-8b80-4793-8849-b910863122e7",
            "sourceColumn": "Employee Lookup[staff_id]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "first_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2b25cb02-c56c-4675-beff-39208fec9b11",
            "sourceColumn": "Employee Lookup[first_name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "last_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e650a8a8-b582-48ae-b847-dc164851c8a8",
            "sourceColumn": "Employee Lookup[last_name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "position",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "dfceab9d-79d3-495b-9f89-758cdad9405b",
            "sourceColumn": "Employee Lookup[position]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "start_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "39ae54cf-1cf0-4562-bb8d-61cdbfa59572",
            "sourceColumn": "Employee Lookup[start_date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3289c083-16e1-4829-a05a-d37fb36404ae",
            "sourceColumn": "Employee Lookup[location]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "038da0cf-d6b6-45f2-b533-00e46e432983",
        "partitions": [
          {
            "name": "ADDCOLUMNS Demo",
            "mode": "import",
            "source": {
              "expression": [
                "",
                " ADDCOLUMNS(",
                "    FILTER(",
                "        'Employee Lookup',",
                "        'Employee Lookup'[staff_id] IN {6,16,31}",
                "    ),",
                "    \"Manager Name & Store\",",
                "    'Employee Lookup'[first_name] & \" \" & 'Employee Lookup'[last_name] & \"-\" & 'Employee Lookup'[location]",
                " )",
                " "
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "SUMMARIZED Demo",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f0668a28948f4ac2abb14b2c09f7dafd"
          }
        ],
        "columns": [
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "11ddc647-f1c8-4565-9a56-785d7bdcaf5d",
            "sourceColumn": "Sales by Store[customer_id]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "quantity_sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "25ca4eb7-9efb-4309-bab4-79452cafe9c1",
            "sourceColumn": "Sales by Store[quantity_sold]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "70d2e114-5fc9-4b1b-bd3f-973988076498",
        "partitions": [
          {
            "name": "SUMMARIZED Demo",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZE(",
                "    FILTER(",
                "        'Sales by Store',",
                "        'Sales by Store'[quantity_sold] >=3",
                "    ),",
                "    'Sales by Store'[customer_id],",
                "    'Sales by Store'[quantity_sold]",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Unsold Pastries",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "56f53c96b697464e93a1734014ac1fd1"
          }
        ],
        "columns": [
          {
            "name": "transaction_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a570400f-4b4c-4b89-b660-b63d01bea361",
            "sourceColumn": "Food Inventory[transaction_date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "store_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4e2bd86a-a6b4-4a13-a0fd-8eef86829570",
            "sourceColumn": "Food Inventory[store_id]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "quantity_sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4eb868e9-a310-4b79-ad77-0a4964f19395",
            "sourceColumn": "Food Inventory[quantity_sold]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "quantity_start_of_day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4c4044c2-0759-4273-a58a-d7adef7d39b9",
            "sourceColumn": "Food Inventory[quantity_start_of_day]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "current_retail_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a2d64b8f-ab5d-4762-9427-13f12096b166",
            "sourceColumn": "Product Lookup[current_retail_price]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1928c83c-92b9-49ba-8765-886c0670a5a6",
            "sourceColumn": "Product Lookup[product]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "7377491a-09a6-4d4a-9514-f7f436b3fb96",
        "partitions": [
          {
            "name": "Unsold Pastries",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZE(",
                "    FILTER(",
                "        'Food Inventory',",
                "        'Food Inventory'[quantity_sold] <> 'Food Inventory'[quantity_start_of_day]",
                "    ),",
                "    'Food Inventory'[transaction_date],",
                "    'Food Inventory'[store_id],",
                "    'Food Inventory'[quantity_sold],",
                "    'Food Inventory'[quantity_start_of_day],",
                "    'Product Lookup'[current_retail_price],",
                "    'Product Lookup'[product]",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Row Demo",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8b75c5dfaf90424ea137f7cb02daf5f9"
          }
        ],
        "columns": [
          {
            "name": "Customer Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "66804f8a-4762-4072-96e2-078f84763f3b",
            "sourceColumn": "[Customer Sales]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Items Ordered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9912de21-5a26-4f26-aa13-052b4607df9d",
            "sourceColumn": "[Items Ordered]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6b759231-8d63-47bf-bd3a-f59aefe65dbe",
        "partitions": [
          {
            "name": "Row Demo",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "ROW(",
                "    \"Customer Sales\", [Customer Sales],",
                "    \"Items Ordered\", ",
                "    SUMX(",
                "        'Sales by Store',",
                "        'Sales by Store'[quantity_sold]",
                "    )",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DATATABLE Demo",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "53353c947b914578abdde67fad6a3721"
          }
        ],
        "columns": [
          {
            "name": "Test Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c5d8de37-f205-4aaf-8907-75ecd7855a2c",
            "sourceColumn": "[Test Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Heads | Tails",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "99aad039-9678-46c6-9ab8-39b45ce7cbd3",
            "sourceColumn": "[Heads | Tails]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Trial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "21b5fc77-eba7-49d5-a0c4-124aeb78e62a",
            "sourceColumn": "[Trial]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "151665b6-0030-4b39-a95d-e6b6bf1ce320",
        "partitions": [
          {
            "name": "DATATABLE Demo",
            "mode": "import",
            "source": {
              "expression": [
                "",
                " DATATABLE(",
                "    \"Test Number\",INTEGER,",
                "    \"Heads | Tails\",STRING,",
                "    \"Trial\",INTEGER,",
                "    {",
                "        {1,\"Heads\",1},",
                "        {2,\"Tails\",1},",
                "        {3,\"Tails\",1}",
                "",
                "    }",
                " )"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "GENERATESERIES Demo",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bd63cdc49833454385e47f3ef67984f9"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b5f5791b-cfc9-45d1-8621-c183dadb0dfe",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6200c658-e7cf-4a2a-b94c-976f7ca17c09",
        "partitions": [
          {
            "name": "GENERATESERIES Demo",
            "mode": "import",
            "source": {
              "expression": [
                "",
                " GENERATESERIES(",
                "    -50.5,",
                "    50.5",
                " )"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Table Constructor Demo",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "62904e90a9344285a023bad6e9866c8e"
          }
        ],
        "columns": [
          {
            "name": "Value1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "432e4daf-f3f1-419c-982b-4af51c75e0cb",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e0c5d565-e3f3-48db-9a6c-5b9d632f2735",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f80be031-571f-4231-9fd9-dda90abe7a9e",
        "partitions": [
          {
            "name": "Table Constructor Demo",
            "mode": "import",
            "source": {
              "expression": [
                "",
                " {",
                "    (\"Customer 1\",FORMAT(CALCULATE([Customer Sales],'Customer Lookup'[customer_id] = 1),\"CURRENCY\")),",
                "    (\"Customer 79\",FORMAT(CALCULATE([Customer Sales],'Customer Lookup'[customer_id] = 79),\"CURRENCY\"))",
                " }"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Target Sales - April 2019 (DATATABLE)",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c393879c64894a36b013f6b1e4875798"
          }
        ],
        "columns": [
          {
            "name": "Store ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "cbbca931-1e46-426f-bf94-0d65add2c695",
            "sourceColumn": "[Store ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0a03a147-4497-4ebd-bc44-ebcf9108e94d",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4ba7a391-03e0-48b7-919c-d99eaa211ccd",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Bean/Teas Goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0bc0942d-85ec-434b-84ed-8984a87a1dad",
            "sourceColumn": "[Bean/Teas Goal]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Beverage Goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9e722a9c-ce60-4a8f-915b-bd8a5a5107bb",
            "sourceColumn": "[Beverage Goal]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Food Goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "15481575-c404-4587-ab7c-4a93eadcc90b",
            "sourceColumn": "[Food Goal]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Merchandise Goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b17f27e2-49cc-4bf8-a549-6a2132dfa418",
            "sourceColumn": "[Merchandise Goal]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "68b3b5e9-bcb6-481e-839e-d380a299dc12",
        "partitions": [
          {
            "name": "Target Sales - April 2019 (DATATABLE)",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DATATABLE(",
                "    \"Store ID\",INTEGER,",
                "    \"Year\",STRING,",
                "    \"Month\",STRING,",
                "    \"Bean/Teas Goal\", INTEGER,",
                "    \"Beverage Goal\",INTEGER,",
                "    \"Food Goal\",INTEGER,",
                "    \"Merchandise Goal\",INTEGER,",
                "    {",
                "        {3,\"2019\",\"April\",268,15608,1964,80},",
                "        {5,\"2019\",\"April\",277,14687,2020,91},",
                "        {8,\"2019\",\"April\",377,15011,1973,34}",
                "    }",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}