{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0 (24.06)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Categories\",\"Geography\",\"Sales rep\",\"ProductDetails\",\"SubCategory\",\"Sales\",\"Sample File\",\"Parameter1\",\"Transform Sample File\",\"Transform File\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Transform Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(Parameter1,[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "f75ff208-f351-4d99-8f67-780c574dae95",
        "queryGroup": "Transform File from Sales"
      },
      {
        "name": "Parameter1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "e59fd9ef-65f6-4075-802e-b1764e728cab",
        "queryGroup": "Transform File from Sales\\Helper Queries"
      },
      {
        "name": "Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\EndToEndProjectYouTube\\Data\\Sales\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "2e252d19-145a-4241-b5b6-9f2b2c1eb234",
        "queryGroup": "Transform File from Sales\\Helper Queries"
      },
      {
        "name": "Transform File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter1 as binary) => let",
          "    Source = Csv.Document(Parameter1,[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "ee6d8340-77a8-41bf-8f83-dc4166566d82",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File\"\"}\" ]",
        "queryGroup": "Transform File from Sales\\Helper Queries"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Sales"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Sales\\Helper Queries"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_83af90b7-2c29-4620-9db9-25f0a551c722",
        "fromColumn": "Sub Category Key",
        "fromTable": "ProductDetails",
        "toColumn": "SubCategoryKey",
        "toTable": "SubCategory"
      },
      {
        "name": "AutoDetected_519627a5-9d80-4184-8977-20bbde1159bb",
        "fromColumn": "GeoKey",
        "fromTable": "Sales",
        "toColumn": "GeoKey",
        "toTable": "Geography"
      },
      {
        "name": "fe739e04-6744-4a30-4589-02269de95fcd",
        "fromColumn": "SalesRepID",
        "fromTable": "Sales",
        "toColumn": "SalesRepID",
        "toTable": "Sales rep"
      },
      {
        "name": "29e94692-9693-2a90-e156-19d0d0d873d1",
        "fromColumn": "CategoryKey",
        "fromTable": "SubCategory",
        "toColumn": "CategoryKey",
        "toTable": "Categories"
      },
      {
        "name": "aa0685ad-8f63-534f-21ee-0cbc0be7d780",
        "fromColumn": "ProductID",
        "fromTable": "Sales",
        "toColumn": "ProductID",
        "toTable": "ProductDetails"
      },
      {
        "name": "b9259f39-f2c1-cc3a-4715-cc0192753caa",
        "fromColumn": "Date",
        "fromTable": "Sales",
        "toColumn": "Date",
        "toTable": "DateMaster"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Categories",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7a27b82b-5dc4-4cdb-856f-1976528a3e95",
            "sourceColumn": "CategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d615fefd-a632-461e-a482-0691c8339ba1",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "abc93aaa-899c-44c7-98aa-28af0fe4171a",
        "measures": [
          {
            "name": "Total Rev",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              " SUM(Sales[Total Revenue]",
              " )"
            ],
            "lineageTag": "e917aa90-bcd6-41c8-81f5-b8808ef15a1c"
          },
          {
            "name": "Prev Qtr",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              " CALCULATE(",
              "    [Total Rev],",
              "    PREVIOUSQUARTER(DateMaster[Date]",
              "    ))"
            ],
            "lineageTag": "0b65a90c-4042-4f73-ac06-2557bdcc447a"
          },
          {
            "name": "QoQ Growth",
            "expression": [
              "",
              "  ([Total Rev] - [Prev Qtr]) / [Prev Qtr]",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "08a72dde-eeb2-419c-afd9-38851c1fe828"
          },
          {
            "name": "Tot Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUM(Sales[Gross Profit]",
              ")"
            ],
            "lineageTag": "c82276eb-888b-462f-bbdd-e53b225275a3"
          },
          {
            "name": "Prev Month Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([Tot Profit],",
              "PREVIOUSMONTH(DateMaster[Date]",
              "))"
            ],
            "lineageTag": "8ad5daef-1369-4d43-97d4-c8a9d1a6b590"
          },
          {
            "name": "MoM Growth",
            "expression": "([Tot Profit] - [Prev Month Profit]) / [Prev Month Profit]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "973e5a48-02ec-4db2-a479-2263a39695f0"
          }
        ],
        "partitions": [
          {
            "name": "Categories",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\EndToEndProjectYouTube\\Data\\Dimensions\\Categories.xlsx\"), null, true),",
                "    Categories_Sheet = Source{[Item=\"Categories\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Categories_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CategoryKey\", Int64.Type}, {\"Category\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Geography",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef0bff46-5e35-4d0c-b45f-3cd9a7da35a2",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Town",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfd3a50a-5e5b-4359-893d-9af889c1b04d",
            "sourceColumn": "Town",
            "summarizeBy": "none"
          },
          {
            "name": "Wikipedia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3edd061d-729c-4757-99f0-f2060b0aa0b6",
            "sourceColumn": "Wikipedia",
            "summarizeBy": "none"
          },
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fe6eff64-1207-490f-8324-1654acaec5bf",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0ee53438-3a4e-4bc8-9fd0-b74c875cb7f1",
        "partitions": [
          {
            "name": "Geography",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\EndToEndProjectYouTube\\Data\\Dimensions\\Geography.xlsx\"), null, true),",
                "    Geography_Sheet = Source{[Item=\"Geography\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Geography_Sheet,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Country\", type text}, {\"Town\", type text}, {\"Wikipedia\", type text}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Changed Type1\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"GeoKey\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales rep",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "SalesRepID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eaa24b8e-2ebb-4449-a080-759774f4ff1b",
            "sourceColumn": "SalesRepID",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Rep Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17131b0d-c456-4290-8f1f-beaf39d24324",
            "sourceColumn": "Sales Rep Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fa72c9eb-0bea-4a22-914d-9574cf0f7127",
        "partitions": [
          {
            "name": "Sales rep",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\EndToEndProjectYouTube\\Data\\Dimensions\\SalesRep.xlsx\"), null, true),",
                "    #\"Sales rep_Sheet\" = Source{[Item=\"Sales rep\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Sales rep_Sheet\",{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SalesRepID\", type text}, {\"Sales Rep Name\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type1\",\"ID -\",\"\",Replacer.ReplaceText,{\"SalesRepID\"})",
                "in",
                "    #\"Replaced Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ProductDetails",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d9253037-7b00-49ae-b94b-b75473b9c267",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Category Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "17857926-6893-4f8d-9c3d-bf01c9c24502",
            "sourceColumn": "Sub Category Key",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9bf0a00c-40e4-4d62-846f-d0441a59fa9a",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "ProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "792a2477-8427-4b69-bf7d-ae01a84f0696",
            "sourceColumn": "ProductName",
            "summarizeBy": "none"
          },
          {
            "name": "RetailPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "02b9e5cd-24ef-4c1e-922b-9d7c51cfaaa1",
            "sourceColumn": "RetailPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "StandardCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1af31df1-825f-4542-9ba9-9185a0e0a1f3",
            "sourceColumn": "StandardCost",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "3feb773e-98cb-442a-8f6f-ad6e1acbb709",
        "partitions": [
          {
            "name": "ProductDetails",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\EndToEndProjectYouTube\\Data\\Dimensions\\Product.csv\"),[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductID\", Int64.Type}, {\"Sub Category Key\", Int64.Type}, {\"Color\", type text}, {\"ProductName\", type text}, {\"RetailPrice\", type number}, {\"StandardCost\", type number}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\", {\"ProductID\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SubCategory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "SubCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "81ed8480-7051-468b-8802-234050d66260",
            "sourceColumn": "SubCategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "CategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e241901-bc0c-4689-a1f4-44b604459b11",
            "sourceColumn": "CategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "SubCategory Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddb3e288-dc7f-44cf-8e54-885331afe416",
            "sourceColumn": "SubCategory Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "86f3be43-4ae8-47db-b8f1-0ec304e6e7ae",
        "partitions": [
          {
            "name": "SubCategory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\EndToEndProjectYouTube\\Data\\Dimensions\\SubCategories.xlsx\"), null, true),",
                "    SubCategory_Table = Source{[Item=\"SubCategory\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(SubCategory_Table,{{\"SubCategoryKey\", Int64.Type}, {\"CategoryKey\", type text}, {\"SubCategory Name\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"ID - \",\"\",Replacer.ReplaceText,{\"CategoryKey\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"ID -\",\"\",Replacer.ReplaceText,{\"CategoryKey\"})",
                "in",
                "    #\"Replaced Value1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "fSalesPrimaryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "68113285-190c-4077-a647-f0cde6f94a3b",
            "sourceColumn": "fSalesPrimaryKey",
            "summarizeBy": "count"
          },
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4b0ef402-62a0-4f0d-9362-c55cc0e7a02c",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesRepID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "93712c5b-9db6-4d4d-a14f-cb778b6d3622",
            "sourceColumn": "SalesRepID",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4abf4cc1-419b-4e3b-bb46-e2b40bf7a6c3",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Units",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "af5131c1-cde4-4f5a-be60-fec38cd44b8b",
            "sourceColumn": "Units",
            "summarizeBy": "sum"
          },
          {
            "name": "PercentOfStandardCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "43c838a5-440a-489c-9748-1b29f4c3b8e8",
            "sourceColumn": "PercentOfStandardCost",
            "summarizeBy": "sum"
          },
          {
            "name": "RevenueDiscount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "89774960-264e-4daa-bf13-bb34137c5cb8",
            "sourceColumn": "RevenueDiscount",
            "summarizeBy": "sum"
          },
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1b833eb7-e94b-4546-aaa0-c61ffd7dbb6a",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "Total Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              " Sales[Units] * RELATED(",
              "    ProductDetails[RetailPrice]",
              " )"
            ],
            "formatString": "0.00",
            "isDataTypeInferred": true,
            "lineageTag": "f2788078-325b-4e12-8449-202f0fb73957",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Total Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "Sales[Units] * RELATED(ProductDetails[StandardCost]",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "6ce7aab7-6de0-43d8-b6ef-89f28e152db4",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Gross Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "Sales[Total Revenue] - Sales[Total Cost]"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "46bd2301-845d-490e-b828-0e0fef1966b9",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "c616ba3a-c257-491b-9c21-fca14ecef4e3",
        "partitions": [
          {
            "name": "Sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\Pranav Bhoola\\Desktop\\Pranav_Bhoola\\DatabaseAdministration\\PowerBIReports\\EndToEndProjectYouTube\\Data\\Sales\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File\", each #\"Transform File\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File\"(#\"Sample File\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"fSalesPrimaryKey\", Int64.Type}, {\"ProductID\", Int64.Type}, {\"SalesRepID\", Int64.Type}, {\"Location\", type text}, {\"Date\", type date}, {\"Units\", Int64.Type}, {\"PercentOfStandardCost\", type number}, {\"RevenueDiscount\", type number}}),",
                "    #\"Removed Source Details\" = Table.RemoveColumns(#\"Changed Type\",{\"Source.Name\"}),",
                "    #\"Split Location\" = Table.SplitColumn(#\"Removed Source Details\", \"Location\", Splitter.SplitTextByDelimiter(\";\", QuoteStyle.Csv), {\"Location.1\", \"Location.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Location\",{{\"Location.1\", type text}, {\"Location.2\", type text}}),",
                "    #\"Renamed Columns Location1 to Country, Location2 to Town\" = Table.RenameColumns(#\"Changed Type1\",{{\"Location.1\", \"Country\"}, {\"Location.2\", \"Town\"}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Renamed Columns Location1 to Country, Location2 to Town\", {\"Country\", \"Town\"}, Geography, {\"Country\", \"Town\"}, \"Geography\", JoinKind.LeftOuter),",
                "    #\"Expanded Geography\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Geography\", {\"GeoKey\"}, {\"GeoKey\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Expanded Geography\",{\"fSalesPrimaryKey\", \"ProductID\", \"SalesRepID\", \"GeoKey\", \"Country\", \"Town\", \"Date\", \"Units\", \"PercentOfStandardCost\", \"RevenueDiscount\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"Country\", \"Town\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateMaster",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "46deadb64da645ef9f901bef698731eb"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "11c243d2-1feb-40a0-bb9e-9d7d8383c515",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "YEAR(DateMaster[Date])"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f5546dad-2d77-4451-83c7-e9cc1d21a679",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              " MONTH(DateMaster[Date])"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "681daf40-fb89-4573-9d68-4c0ad15b949e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "FORMAT(DateMaster[Date],",
              "\"MMM\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e4b649e1-8472-46f4-93f7-2a3e82c26c0a",
            "sortByColumn": "Month",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Qtr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "QUARTER(DateMaster[Date])"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "af2464cf-bb0f-4e97-b5e9-66ea61e9ee84",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Week Num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              " WEEKNUM(DateMaster[Date])"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f04fb590-9dfa-4d6a-9fc1-2f0309598a4d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Week Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "WEEKDAY(DateMaster[Date])"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "563fac76-3ed1-4fcf-933d-72752e8e0417",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Week Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "FORMAT(DateMaster[Date],",
              "\"ddd\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "69a85fa3-1fc9-41b9-aa77-d2b3ff99499a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "9a77ed83-0a69-4b67-8113-77de33b9509c",
        "partitions": [
          {
            "name": "DateMaster",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "CALENDAR(",
                "    FIRSTDATE(Sales[Date]),",
                "    LASTDATE(Sales[Date])",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}