# This is a YAML file named "Check MSSQL Database"
name: Check MSSQL Database

# The workflow is triggered when changes are made to the specified file
on:
  push:
    branches:
      - main
    paths:
      - DatabaseAdministration/SQLStatements/UpdateScript.sql

# The workflow defines a single job named "check_database" that runs on a machine with the latest version of Ubuntu
jobs:
  check_database:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout repository code
        uses: actions/checkout@v2

      # Step 2: Download and run MSSQL Docker container
      - name: Download and run MSSQL Docker container
        run: |
          sudo docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=YourStrong@Password122' -p 1433:1433 -d --name mssql-server -v $(pwd):/scripts mcr.microsoft.com/mssql/server:2019-latest

      # Step 3: Wait for MSSQL to start
      - name: Wait for MSSQL to start
        run: |
          sleep 15 

      # Step 4: Run SQL commands to create and populate the database, utilizing secrets for SQL server, username, and password
      - name: Create and Populate Database
        run: |
          sqlcmd -S ${{ secrets.SQL_SERVER }} -U ${{ secrets.SQL_USERNAME }} -P ${{ secrets.SQL_PASSWORD }} -i DatabaseAdministration/SQLStatements/UpdateScript.sql
