name: Deployment

on:
  push:
    branches: [ main ]

env:
  PROFILE: Files
  ENVIRONMENT: PROD

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: PROD
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Display environment variables
        run: echo "Profile: $PROFILE, Environment: $ENVIRONMENT"

      - name: Print deployment configuration
        run: cat DatabaseAdministration/PowerBIReports/EndToEndProjectYouTube/pbi-tools.json

      - name: pbi-tools deploy
        run: /app/pbi-tools/pbi-tools.core deploy DatabaseAdministration/PowerBIReports/EndToEndProjectYouTube "$PROFILE" "$ENVIRONMENT"
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
