name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MSSQL_CONNECTION_STRING: "Server=6.tcp.eu.ngrok.io:19373;Database=StudentDatabase;User Id=Ysa;Password=P@$$word2024;"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSSQL Server connection
      run: echo "Setting up MSSQL connection..."

    - name: Build and test your application
      run: |
        # Your build and test commands go here
        # Example: dotnet build
        # Example: dotnet test
