name: Update Database

on:
  push:
    branches:
      - main

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install -g mssql-cli

      - name: List repository contents
  run: ls -R

    - name: Update Database
      run: |
       crip.sql
